import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
const publicPages=['capstone','pdpl','services','guide','privacy','trust','methodology','faq','validation','stories','about','contact','business-model','changelog','interoperability','mapping','sample-report','advisor','admin']
for(const lang of ['ar','en']){
 test(`shared public navigation and single-language content: ${lang}`,async({page,request})=>{
  test.setTimeout(120_000)
  for(const file of publicPages){
   const path=`/${lang}/${file}.html`
   const response=await request.get(path);expect(response.ok(),path).toBeTruthy()
   const source=await response.text()
   expect(source).not.toContain(`data-kamin-lang="${lang==='ar'?'en':'ar'}"`)
   expect(source).toContain(`hreflang="${lang==='ar'?'en':'ar-SA'}"`)
   await page.goto(path)
   await expect(page.locator('h1:visible')).toHaveCount(1)
   await expect(page.locator('.k-site-header')).toHaveCount(1)
   await expect(page.locator('.k-site-footer')).toHaveCount(1)
   const toggle=page.locator('.k-menu');if(await toggle.isVisible())await toggle.click()
   const nav=page.getByRole('navigation',{name:lang==='ar'?'التنقل الرئيسي':'Main navigation',exact:true})
   await expect(nav.getByRole('link',{name:lang==='ar'?'الخدمات والميزات':'Services & features',exact:true})).toBeVisible()
   await expect(nav.getByRole('link',{name:lang==='ar'?'دليل الاستخدام':'User guide',exact:true})).toBeVisible()
   expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),path).toBe(true)
  }
 })
 test(`localized entry, choices, recovery and no automatic consent: ${lang}`,async({page})=>{
  await page.goto(`/${lang}/`)
  await expect(page.locator('.skip-link')).toHaveText(lang==='ar'?'تجاوز إلى المحتوى':'Skip to content')
  await page.getByRole('button',{name:lang==='ar'?'ابدأ بناء ملفك':'Build your profile',exact:true}).first().click()
  await expect(page.getByRole('checkbox')).not.toBeChecked()
  await page.getByRole('checkbox').check()
  await page.getByRole('button',{name:lang==='ar'?'ابدأ بصمتي':'Start my profile',exact:true}).click()
  await expect(page.locator('input[name="careerInterest"][value=""]')).toBeChecked()
  await page.locator('input[name="careerInterest"][value="investigative"]').check()
  await page.locator('input[name="goal"][value="data"]').check()
  const s=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('kamin-session-v3')))
  expect(s.consents).toMatchObject({insight:true,analyze:false,advisor:false,research:false})
  expect(s.courses).toEqual([])
  const report=await new AxeBuilder({page}).analyze()
  expect(report.violations.filter(v=>['serious','critical'].includes(v.impact)),JSON.stringify(report.violations)).toEqual([])
 })
 test(`network tour leaves personal state untouched: ${lang}`,async({page})=>{
  await page.goto(`/${lang}/`)
  await page.locator('.network-tour button').click()
  for(let i=1;i<=4;i++){
   await expect(page.locator('.network-tour strong')).toContainText(`${i}/4`)
   await page.getByRole('button',{name:i===4?(lang==='ar'?'إنهاء الجولة':'Finish tour'):(lang==='ar'?'التالي':'Next'),exact:true}).click()
  }
  expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBeNull()
 })
}
test('storage quota failure is visible and does not crash the profile',async({page})=>{
 await page.addInitScript(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='kamin-session-v3')throw new DOMException('Storage full','QuotaExceededError');return original.call(this,key,value)}})
 await page.goto('/?lang=en&start=profile')
 await page.getByRole('checkbox').check()
 await page.getByRole('button',{name:'Start my profile',exact:true}).click()
 await page.locator('input[name="goal"][value="data"]').check()
 await expect(page.getByRole('alert')).toContainText('could not be saved')
 await page.getByRole('button',{name:'Open saving & backup options'}).click()
 await expect(page.getByRole('heading',{name:'You control your data'})).toBeVisible()
})
test('device storage failure is reported without a false saved confirmation',async({page})=>{
 await page.addInitScript(()=>{IDBFactory.prototype.open=function(){throw new DOMException('Storage blocked','SecurityError')}})
 await page.goto('/?lang=en&start=profile')
 await page.getByRole('checkbox').check()
 await page.getByRole('button',{name:'Start my profile',exact:true}).click()
 await page.getByRole('button',{name:'Profile saving options',exact:true}).click()
 await page.getByRole('button',{name:'Keep my profile on this device',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('Storage is unavailable')
 expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('kamin-session-v3')).localPersistence)).toBe(false)
})
test('static content exposes security headers and English metadata without running JavaScript',async({request})=>{
 const response=await request.get('/en/guide.html'),headers=response.headers(),html=await response.text()
 expect(headers['content-security-policy']).toContain("frame-ancestors 'none'")
 expect(headers['content-security-policy'].split('script-src')[1].split(';')[0]).not.toContain('unsafe-inline')
 expect(headers['x-frame-options']).toBe('DENY')
 expect(html).toContain('<title>User guide | Kamin</title>')
 expect(html).toContain('og-kamin-en.jpg')
 expect(html).not.toContain('data-kamin-lang="ar"')
})
test('empty comparison offers courses and a working two-course starting point',async({page})=>{
 await page.goto('/?lang=ar')
 await page.getByRole('button',{name:'جرّب المثال التوضيحي',exact:true}).first().click()
 await page.getByRole('dialog').getByRole('button',{name:'جرّب المثال التوضيحي',exact:true}).click()
 await page.getByRole('checkbox',{name:/أوافق صراحةً/}).check()
 await page.getByRole('button',{name:/أعتمد السجل/}).click()
 const more=page.getByRole('button',{name:'المزيد',exact:true});if(await more.isVisible())await more.click()
 await page.getByRole('button',{name:'المقارنة',exact:true}).first().click()
 await expect(page.getByRole('button',{name:'اختر الدورات',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'قارن اقتراحين',exact:true}).click()
 await expect(page.locator('.compare-table thead th')).toHaveCount(3)
})

test('a match opens its own development plan without inventing evidence',async({page})=>{
 await page.goto('/?lang=en&start=profile')
 await page.getByRole('checkbox').check()
 await page.getByRole('button',{name:'Start my profile',exact:true}).click()
 await page.locator('input[name="goal"][value="cyber"]').check()
 await page.getByRole('button',{name:'Matches',exact:true}).first().click()
 const card=page.locator('.match-card').filter({has:page.getByRole('heading',{name:'Junior Cybersecurity Analyst',exact:true})})
 const before=await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))
 await card.getByRole('button',{name:'Open this pathway’s plan',exact:true}).click()
 await expect(page.getByLabel('Pathway to explore')).toHaveValue('job-cyber-analyst')
 await expect(page.getByRole('tab',{name:'Development plan',exact:true})).toHaveAttribute('aria-selected','true')
 expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBe(before)
})

test("published team plan and AI status match the released baseline",async({page})=>{
 await page.goto("/en/capstone.html")
 await expect(page.getByRole("main")).toContainText("three-college")
 await expect(page.getByRole("main")).toContainText("two HR managers")
 const report=await new AxeBuilder({page}).analyze()
 expect(report.violations.filter(v=>["serious","critical"].includes(v.impact)),JSON.stringify(report.violations)).toEqual([])
 await page.goto("/en/services.html")
 const card=page.locator("article").filter({has:page.getByRole("heading",{name:"Pathway discovery & AI",exact:true})})
 await expect(card).toContainText("Working pilot + planned extensions")
 await expect(card).toContainText("runs locally")
 await page.goto("/ar/services.html")
 await expect(page.getByRole("main")).toContainText("تجربة عاملة + تطوير مخطط")
})
