import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
async function openLab(page){
  await page.goto('/?lang=ar')
  await page.getByLabel('ابحث في المعرفة المرجعية',{exact:true}).fill('قواعد البيانات')
  await page.getByRole('button',{name:'استكشف',exact:true}).click()
  await expect(page.locator('.knowledge-detail h3')).toHaveText('قواعد البيانات')
  await page.getByRole('tab',{name:'مختبر SPARQL',exact:true}).click()
}
async function run(page){await page.getByRole('button',{name:'شغّل الاستعلام',exact:true}).click();await expect(page.getByRole('heading',{name:'نتيجة الاستعلام',exact:true})).toBeVisible({timeout:20000})}
test('reference search and real browser SPARQL work without a student profile',async({page})=>{
  await openLab(page)
  await expect(page.getByLabel('نطاق البيانات')).toHaveValue('reference')
  await run(page)
  await expect(page.locator('.query-table [title="urn:kamin:skill:database"]').first()).toBeVisible()
  await page.getByLabel('استعلام SPARQL — قابل للتعديل',{exact:true}).fill('ASK { GRAPH <urn:kamin:graph:reference> { ?s <urn:kamin:requiresCapability> ?o } }')
  await expect(page.locator('.query-table')).toHaveCount(0)
  await run(page)
  await expect(page.locator('.query-answer')).toContainText('نعم')
  expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBeNull()
})
test('synthetic profile queries and JSON export are explicitly scoped and do not populate the student file',async({page})=>{
  await openLab(page)
  await page.getByLabel('ابدأ بسؤال جاهز').selectOption('inferred')
  await run(page)
  await expect(page.locator('.query-results')).toContainText('لا توجد نتائج')
  await page.getByLabel('نطاق البيانات').selectOption('demo')
  await run(page)
  await expect(page.locator('.query-table [title="urn:kamin:hasInterestContextFor"]').first()).toBeVisible()
  const pending=page.waitForEvent('download')
  await page.getByRole('button',{name:'تنزيل النتائج JSON',exact:true}).click()
  expect((await pending).suggestedFilename()).toBe('kamin-query-results.json')
  expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBeNull()
})
test('SERVICE and updates are blocked before any external request',async({page})=>{
  await openLab(page)
  const outbound=[];page.on('request',r=>{if(r.url().includes('query-private.invalid'))outbound.push(r.url())})
  await page.locator('#sparql-query').fill('SELECT * WHERE { OPTIONAL { SERVICE <https://query-private.invalid> { ?s ?p ?o } } }')
  await page.getByRole('button',{name:'شغّل الاستعلام',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('SERVICE وFROM غير متاحين',{timeout:20000})
  expect(outbound).toEqual([])
  await page.locator('#sparql-query').fill('DELETE WHERE { ?s ?p ?o }')
  await page.getByRole('button',{name:'شغّل الاستعلام',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('للقراءة فقط')
})
test('personal queries require fresh local permission and clearing it removes the visible results',async({page})=>{
  await page.goto('/?lang=ar')
  await page.getByRole('button',{name:'ابدأ بناء ملفك',exact:true}).first().click()
  await page.getByRole('checkbox',{name:/أوافق على بناء ملف Person 360/}).check()
  await page.getByRole('button',{name:'ابدأ بصمتي',exact:true}).click()
  await expect(page.getByLabel('درجة هيكلة العمل')).toBeHidden()
  await page.locator('input[type="radio"][name="goal"][value="data"]').check()
  const more=page.getByRole('button',{name:'المزيد',exact:true});if(await more.isVisible())await more.click()
  await page.getByRole('button',{name:'مستكشف المعرفة',exact:true}).click()
  await page.getByRole('tab',{name:'مختبر SPARQL',exact:true}).click()
  await page.getByLabel('نطاق البيانات').selectOption('personal')
  await expect(page.getByRole('button',{name:'شغّل الاستعلام',exact:true})).toBeDisabled()
  const consent=page.getByRole('checkbox',{name:/أسمح بقراءة ملفي محليًا/})
  await consent.check()
  await page.getByLabel('ابدأ بسؤال جاهز').selectOption('inferred')
  await run(page)
  await expect(page.locator('.query-table [title="urn:kamin:hasGoalContextFor"]').first()).toBeVisible()
  await consent.uncheck()
  await expect(page.locator('.query-results')).toBeEmpty()
  await expect(page.getByRole('button',{name:'شغّل الاستعلام',exact:true})).toBeDisabled()
  const state=await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))
  expect(state).not.toContain('SELECT')
  expect(state).not.toContain('allowPersonal')
})
test('knowledge tools remain accessible and fit mobile and English layouts',async({page})=>{
  await page.goto('/?lang=en')
  await page.getByLabel('Search reference knowledge',{exact:true}).fill('data')
  await page.getByRole('button',{name:'Explore',exact:true}).click()
  await expect(page.locator('.knowledge-detail')).toBeVisible()
  await page.getByRole('tab',{name:'SPARQL lab',exact:true}).click()
  await page.getByRole('button',{name:'Run query',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Query result',exact:true})).toBeVisible({timeout:20000})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  const a=await new AxeBuilder({page}).analyze()
  expect(a.violations.filter(v=>['serious','critical'].includes(v.impact)),JSON.stringify(a.violations)).toEqual([])
})
