import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
async function startProfile(page, lang='ar'){
 await page.goto(`/?lang=${lang}`)
 await page.getByRole('button',{name:lang==='ar'?'ابدأ بناء ملفك':'Build your profile',exact:true}).first().click()
 await page.getByRole('checkbox',{name:lang==='ar'?/أوافق على بناء ملف Person 360/:/I consent to building my Person 360/}).check()
 await page.getByRole('button',{name:lang==='ar'?'ابدأ بصمتي':'Start my profile',exact:true}).click()
}
test('interests build a visible network before any transcript and never become evidence',async({page})=>{
 await startProfile(page)
 await page.locator('input[type="radio"][name="goal"][value="data"]').check()
 await page.locator('input[type="radio"][name="careerInterest"][value="investigative"]').check()
 await page.locator('.optional-preferences > summary').click()
 await page.getByLabel('طريقة التعلم المفضلة',{exact:true}).selectOption('project-based')
 const dialog=page.getByRole('dialog')
 await expect(dialog.locator('.profile-node').filter({hasText:'اهتماماتك'})).toContainText('تحليلي واستقصائي')
 await expect(dialog.locator('.profile-node').filter({hasText:'طريقة تعلّمك'})).toContainText('بالمشاريع')
 const state=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('kamin-session-v3')))
 expect(state.approved).toBe(false)
 expect(state.courses).toEqual([])
 expect(state.goal).toBe('data')
 await page.getByRole('button',{name:'استكشف شبكتي',exact:true}).click()
 await expect(dialog.locator('.profile-network')).toContainText('تحليلي واستقصائي')
 await page.getByRole('tab',{name:'مساعد القرار',exact:true}).click()
 await expect(page.locator('.guide-answer')).toContainText('الاهتمام المهني الذي اخترته متوافق')
 await page.getByLabel('اختر سؤالك').selectOption('missing')
 await expect(page.locator('.guide-answer')).toContainText('لا يوجد حتى الآن مسار دليل')
 await page.getByRole('button',{name:'راجع معلومات سجلي',exact:true}).click()
 await expect(page.locator('.onboarding-upload')).toBeVisible()
})
test('optional interests can be cleared and remain cleared after returning',async({page})=>{
 await startProfile(page)
 await page.locator('input[type="radio"][name="careerInterest"][value="artistic"]').check()
 await page.locator('input[type="radio"][name="careerInterest"][value=""]').check()
 await page.getByRole('button',{name:'إغلاق',exact:true}).click()
 await page.getByRole('button',{name:'ابدأ بناء ملفك',exact:true}).first().click()
 await expect(page.locator('input[name="careerInterest"][value=""]')).toBeChecked()
 await expect(page.getByRole('dialog').locator('.profile-node').filter({hasText:'اهتماماتك'})).toContainText('لم تحدد بعد')
})
test('profile choices and network are accessible in both languages',async({page})=>{
 await startProfile(page,'en')
 await page.locator('input[type="radio"][name="careerInterest"][value="social"]').check()
 await page.locator('input[type="radio"][name="goal"][value="product"]').check()
 await expect(page.getByRole('dialog').locator('.profile-node').filter({hasText:'Interests'})).toContainText('Social / helping')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const report=await new AxeBuilder({page}).analyze()
 expect(report.violations.filter(v=>['serious','critical'].includes(v.impact)),JSON.stringify(report.violations)).toEqual([])
 await page.getByRole('button',{name:'Close',exact:true}).click()
 await page.getByRole('button',{name:'Switch to Arabic',exact:true}).click()
 await page.getByRole('button',{name:'ابدأ بناء ملفك',exact:true}).first().click()
 await expect(page.locator('input[name="careerInterest"][value="social"]')).toBeChecked()
 await expect(page.getByRole('dialog').locator('.profile-node').filter({hasText:'اهتماماتك'})).toContainText('مساعدة وتطوير الآخرين')
})
