import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test('multi-hop people and project connections are explicit synthetic examples',async({page})=>{
 await page.goto('/?lang=ar')
 await page.getByRole('button',{name:'مع من يمكنني التعاون؟',exact:true}).click()
 await expect(page.locator('.relationship-trail')).toContainText('عمر')
 await expect(page.locator('.relationship-trail')).toContainText('مشروع لوحة بيانات')
 await expect(page.locator('.relationship-path')).toContainText('ليس ترشيحًا لشخص حقيقي')
 await page.getByText('افحص علاقات المسار ومصادرها',{exact:true}).click()
 await expect(page.locator('.relationship-path li')).toHaveCount(4)
 expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBeNull()
})
test('academic withdrawal and pathway changes update connected nodes without invented evidence',async({page})=>{
 await page.goto('/?lang=ar')
 await page.getByLabel('تضمين دليل أكاديمي وهمي',{exact:true}).uncheck()
 await expect(page.locator('.relationship-map .relationship-evidence')).toContainText('غير متاح')
 await expect(page.locator('.relation-evidence')).toHaveCount(0)
 await expect(page.locator('.relationship-path')).toContainText('لا يوجد مسار دليل')
 await page.getByLabel('جرّب مسارًا آخر',{exact:true}).selectOption('job-cyber-analyst')
 await expect(page.locator('.relationship-map .relationship-job')).toContainText('سيبراني')
 await expect(page.locator('.relationship-trail')).toContainText('الأمن السيبراني')
})
test('home navigation opens bilingual guide and service pages with accurate status',async({page})=>{
 await page.goto('/?lang=ar')
 const menu=page.getByRole('button',{name:'فتح القائمة',exact:true});if(await menu.isVisible())await menu.click()
 await page.getByRole('link',{name:'دليل الاستخدام',exact:true}).click()
 await expect(page.locator('h1:visible')).toHaveText('دليل الاستخدام')
 await expect(page.getByRole('main')).toContainText('احفظ ملفك وعد إليه')
 const publicMenu=page.locator('.k-menu');if(await publicMenu.isVisible())await publicMenu.click()
 await page.getByRole('link',{name:'الخدمات والميزات',exact:true}).click()
 await expect(page.locator('h1:visible')).toHaveText('الخدمات والميزات')
 const ai=page.locator('article:visible').filter({hasText:'الذكاء الاصطناعي المتقدم'})
 await expect(ai).toContainText('ضمن خطة التطوير')
 await page.locator('[data-language-toggle]').click()
 await expect(page.locator('html')).toHaveAttribute('dir','ltr')
 await expect(page.locator('h1:visible')).toHaveText('Services & features')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const a=await new AxeBuilder({page}).analyze();expect(a.violations.filter(v=>['serious','critical'].includes(v.impact)),JSON.stringify(a.violations)).toEqual([])
})
test('English network remains keyboard accessible without mobile page overflow',async({page})=>{
 await page.goto('/?lang=en')
 await page.getByRole('button',{name:'Who could I collaborate with?',exact:true}).click()
 await expect(page.locator('.relationship-trail')).toContainText('Omar')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const a=await new AxeBuilder({page}).analyze();expect(a.violations.filter(v=>['serious','critical'].includes(v.impact)),JSON.stringify(a.violations)).toEqual([])
})
