import {test,expect} from '@playwright/test'
import oxigraph from 'oxigraph'
import AxeBuilder from '@axe-core/playwright'
async function profile(page){
 await page.goto('/en/?start=profile')
 await page.getByRole('checkbox',{name:/I consent to building my Person 360/}).check()
 await page.getByRole('button',{name:'Start my profile',exact:true}).click()
}
async function lab(page){await page.goto('/en/?view=knowledge');await page.getByRole('tab',{name:'SPARQL lab',exact:true}).click()}
async function bytes(download){const stream=await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);return Buffer.concat(chunks).toString('utf8')}
test('SPARQL syntax errors stay in the result panel, identify location and recover on correction',async({page})=>{
 await lab(page)
 await page.getByRole('button',{name:'Run query',exact:true}).click()
 await expect(page.locator('.query-table')).toBeVisible({timeout:20000})
 await expect(page.locator('.query-table')).not.toContainText('urn:kamin:')
 await expect(page.locator('.query-table [title="urn:kamin:skill:database"]').first()).toContainText('Database')
 await page.getByLabel('SPARQL query — editable',{exact:true}).fill('SELECT * WHERE {\n?s ?p\n}')
 await page.getByRole('button',{name:'Run query',exact:true}).click()
 const panel=page.locator('.query-results')
 await expect(panel.getByRole('alert')).toContainText('Line 3, column 1',{timeout:20000})
 await expect(panel).toContainText('Your data are unchanged')
 await expect(panel.locator('.query-table')).toHaveCount(0)
 await page.getByLabel('SPARQL query — editable',{exact:true}).fill('ASK { ?s ?p ?o }')
 await page.getByRole('button',{name:'Run query',exact:true}).click()
 await expect(panel).toContainText('Yes — the pattern has a match')
 await expect(panel.getByRole('alert')).toHaveCount(0)
})
test('CSV and graph downloads contain real data with scoped named-graph preservation',async({page,context})=>{
 await lab(page)
 await page.getByRole('button',{name:'Run query',exact:true}).click()
 await expect(page.locator('.query-table')).toBeVisible({timeout:20000})
 let pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download CSV',exact:true}).click()
 expect(await bytes(await pending)).toContain('urn:kamin:skill:database')
 await context.grantPermissions(['clipboard-read','clipboard-write'])
 await page.getByRole('button',{name:'Copy as CSV',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('Results copied as CSV')
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('"pathway","capability"')
 await page.getByText('Export the graph for research',{exact:true}).click()
 pending=page.waitForEvent('download');await page.getByRole('button',{name:'Turtle (.ttl)',exact:true}).click()
 const turtle=await bytes(await pending),store=new oxigraph.Store()
 try{store.load(turtle,{format:'text/turtle'});expect(store.size).toBeGreaterThan(100);expect(turtle).not.toContain('urn:kamin:person:local')}finally{store.free()}
 await page.getByLabel('Dataset scope').selectOption('demo')
 pending=page.waitForEvent('download');await page.getByRole('button',{name:'TriG (.trig)',exact:true}).click()
 const trig=await bytes(await pending),dataset=new oxigraph.Store()
 try{dataset.load(trig,{format:'application/trig'});expect(dataset.match(null,null,null,oxigraph.namedNode('urn:kamin:graph:inferred')).length).toBeGreaterThan(0)}finally{dataset.free()}
 expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBeNull()
})
test('encrypted snapshot is reviewed, opened locally, stripped from URL and never merged into a profile',async({page})=>{
 await profile(page)
 await page.locator('input[name="goal"][value="data"]').check()
 await page.getByRole('button',{name:'Profile saving options',exact:true}).click()
 const section=page.locator('.snapshot-share')
 expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('kamin-session-v3')).approved)).toBe(false)
 await expect(section.locator('#snapshot-requirements')).toContainText('To share without a transcript')
 await expect(section.getByRole('button',{name:'Create encrypted link',exact:true})).toBeDisabled()
 await section.getByRole('checkbox',{name:/Include my goal/}).check()
 await expect(section.locator('.snapshot-preview')).toContainText('Data')
 await section.getByRole('checkbox',{name:/I reviewed the snapshot/}).check()
 await section.getByRole('button',{name:'Create encrypted link',exact:true}).click()
 const link=await section.locator('textarea').inputValue()
 expect(link).toContain('#payload=');expect(link).toContain('&key=')
 expect(new URL(link).search).toBe('')
 const before=await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))
 const requests=[];page.on('request',request=>requests.push(request.url()))
 await page.goto(link)
 await expect(page.getByRole('heading',{name:'Shared capability snapshot',exact:true})).toBeVisible()
 expect(new URL(page.url()).hash).toBe('')
 await page.getByRole('button',{name:'Open snapshot locally',exact:true}).click()
 await expect(page.locator('.snapshot-preview')).toContainText('Data')
 expect(requests.some(url=>url.includes('payload=')||url.includes('&key='))).toBe(false)
 expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBe(before)
 const report=await new AxeBuilder({page}).analyze();expect(report.violations.filter(v=>['serious','critical'].includes(v.impact)),JSON.stringify(report.violations)).toEqual([])
 await page.goto('/en/#payload=invalid&key=invalid')
 await expect(page.getByRole('alert')).toContainText('Invalid link format')
 expect(new URL(page.url()).hash).toBe('')
 await expect(page.locator('.snapshot-preview')).toHaveCount(0)
 await page.goto(link)
 await expect(page.getByRole('button',{name:'Open snapshot locally',exact:true})).toBeEnabled()
 await expect(page.locator('.snapshot-preview')).toHaveCount(0)
 await page.getByRole('button',{name:'Open snapshot locally',exact:true}).click()
 await expect(page.locator('.snapshot-preview')).toContainText('Data')
})
test('legacy locale links land on one language path and canonical links stay consistent',async({page})=>{
 await page.goto('/about.html?lang=en')
 await expect(page).toHaveURL(/\/en\/about\.html$/)
 await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','https://kamin-12mf.onrender.com/en/about.html')
 expect(await page.locator('a[href]').evaluateAll(links=>links.filter(a=>a.origin===location.origin&&a.search.includes('lang=')).length)).toBe(0)
 await page.getByRole('button',{name:'Switch to Arabic',exact:true}).click()
 await expect(page).toHaveURL(/\/ar\/about\.html$/)
 await page.goto('/en/pdpl.html')
 await expect(page.locator('.k-doc-table')).toContainText('Partial')
 await expect(page.getByRole('main')).toContainText('not a compliance certificate')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('multilingual WASM recall loads only after opt-in, keeps text local and delegates explanation to the graph',async({page,context})=>{
 test.setTimeout(210000)
 const requests=[];context.on('request',request=>requests.push({url:request.url(),body:request.postData()}))
 await profile(page)
 const section=page.locator('.semantic-recall')
 expect(requests.filter(r=>r.url.includes('/models/'))).toHaveLength(0)
 await section.getByText('Enable local exploration — optional',{exact:true}).click()
 await expect(section.getByRole('button',{name:'Load local model',exact:true})).toBeDisabled()
 await section.getByRole('checkbox').check()
 await section.getByRole('button',{name:'Load local model',exact:true}).click()
 await expect(section.getByRole('button',{name:'Model ready',exact:true})).toBeVisible({timeout:180000})
 const before=await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))
 for(const phrase of ['I enjoy finding patterns in numbers and explaining them','أحب تحليل الأرقام واكتشاف الأنماط في البيانات']){
  await section.locator('textarea').fill(phrase)
  await section.getByRole('button',{name:'Suggest related pathways',exact:true}).click()
  await expect(section.locator('.recall-results')).toContainText(/Data|Analytics|SQL|BI Dashboard/,{timeout:30000})
  expect(JSON.stringify(requests)).not.toContain(phrase)
 }
 expect(requests.filter(r=>new URL(r.url).origin!==new URL(page.url()).origin)).toEqual([])
 expect(await page.evaluate(()=>sessionStorage.getItem('kamin-session-v3'))).toBe(before)
 const target=await section.locator('.recall-results h4').first().innerText()
 await section.getByRole('button',{name:'Inspect pathway and evidence',exact:true}).first().click()
 await expect(page.getByLabel('Pathway to explore')).toContainText(target)
 await page.getByRole('button',{name:'Interests & goal',exact:true}).first().click()
 await page.locator('.semantic-recall').getByText('Enable local exploration — optional',{exact:true}).click()
 await page.getByRole('button',{name:'Stop and delete model files',exact:true}).click()
 expect(await page.evaluate(()=>caches.keys())).not.toContain('kamin-embedding-model-v1')
})
