export const PSYCHOMETRIC_REGISTRY_VERSION='0.2.0'

export const PSYCHOMETRIC_INSTRUMENTS=Object.freeze({
  onetMiniIp30:{
    id:'onet-mini-ip-30',
    name:{ar:'O*NET Mini Interest Profiler (30)',en:'O*NET Mini Interest Profiler (30)'},
    construct:'RIASEC occupational interests',
    dimensions:['Realistic','Investigative','Artistic','Social','Enterprising','Conventional'],
    items:30,
    responseScale:{
      min:1,max:5,
      anchors:['Strongly Dislike','Dislike','Unsure','Like','Strongly Like'],
    },
    officialUrl:'https://www.onetcenter.org/IP.html',
    apiUrl:'https://api-v2.onetcenter.org/mnm/interestprofiler/questions_30',
    sourceSystem:'O*NET Career Exploration Tools',
    status:'approved-model-arabic-adaptation-required',
    decisionRole:'career-interest-fit',
    redistribution:{
      verbatim:'CC BY-ND 4.0 with attribution',
      adapted:'O*NET Tools Developer License',
    },
    notes:{
      ar:'مقياس مهني وليس تشخيصًا نفسيًا. النسخة الرسمية المتاحة إنجليزية/إسبانية؛ لا نفعّل نسخة عربية داخل كامن قبل adaptation موثقة ومراجعة ترخيصها.',
      en:'Career-interest instrument, not a psychological diagnosis. Official web versions are English/Spanish; Kamin does not activate Arabic items until a documented adaptation and license review are complete.',
    },
  },
  ipip50ArabicLevant:{
    id:'ipip-50-arabic-levant',
    name:{ar:'IPIP 50 Big-Five — التكييف العربي المنشور لبلاد الشام',en:'IPIP 50 Big-Five — published Arabic Levant adaptation'},
    construct:'Big Five personality markers',
    dimensions:['Extraversion','Agreeableness','Conscientiousness','Emotional Stability','Openness/Intellect'],
    items:50,
    responseScale:{min:1,max:5,anchors:['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree']},
    officialUrl:'https://ipip.ori.org/ArabicBigFiveFactorMarkers2.htm',
    sourceSystem:'International Personality Item Pool',
    sourceReference:'Zeinoun et al. (2017), Journal of Personality and Social Psychology 113(3):453-465',
    sourceVersion:'2017 Arabic adaptation',
    status:'candidate-for-saudi-validation',
    decisionRole:'low-weight-work-context-only',
    notes:{
      ar:'عينة التحقق المنشورة من لبنان وسوريا والأردن وفلسطين. لا نحول الدرجات إلى percentiles سعودية ولا نستخدمها كبوابة استبعاد.',
      en:'Published validation sample covers Lebanon, Syria, Jordan and Palestine. Do not convert scores into Saudi normative percentiles or use them as an exclusion gate.',
    },
  },
  ipip50ArabicYemen:{
    id:'ipip-50-arabic-yemen',
    name:{ar:'IPIP-BFM-50YE — تكييف عربي يمني',en:'IPIP-BFM-50YE — Yemeni Arabic adaptation'},
    construct:'Big Five personality markers',
    dimensions:['Extraversion','Agreeableness','Conscientiousness','Emotional Stability','Intellect'],
    items:50,
    responseScale:{min:1,max:5,anchors:['Strongly Disagree','Disagree','Neutral','Agree','Strongly Agree']},
    officialUrl:'https://ipip.ori.org/ArabicBigFiveFactorMarkers.htm',
    sourceSystem:'International Personality Item Pool',
    sourceReference:'Almaghbashy (2017), Sana’a University adaptation study',
    sourceVersion:'2017 Yemeni adaptation',
    status:'candidate-for-saudi-validation',
    decisionRole:'low-weight-work-context-only',
    notes:{
      ar:'اختُبر على طلبة جامعة في اليمن؛ مفيد كمقارنة بحثية وليس كنظام معياري سعودي جاهز.',
      en:'Evaluated with a university sample in Yemen; useful as a research comparison, not a ready Saudi normative instrument.',
    },
  },
  onetWorkStyles31:{
    id:'onet-work-styles-31',
    name:{ar:'O*NET 31.0 Work Styles',en:'O*NET 31.0 Work Styles'},
    construct:'Occupation-linked work-style requirements/tendencies',
    officialUrl:'https://www.onetcenter.org/database.html',
    sourceSystem:'O*NET Database',
    sourceVersion:'31.0',
    status:'occupation-reference-model',
    decisionRole:'person-environment-fit',
    notes:{
      ar:'هذه ratings للمهن وليست اختبارًا للفرد. نستخدمها لوصف متطلبات البيئة/المهنة ومقارنتها بملاحظات فردية متحققة من أداة منفصلة.',
      en:'These are occupation ratings, not a person assessment. Use them to describe occupational environments and compare them with separately validated person observations.',
    },
  },
  legacyOnetWorkValues:{
    id:'onet-work-values-legacy',
    name:{ar:'O*NET Work Values — مرجع تاريخي',en:'O*NET Work Values — legacy reference'},
    construct:'Work values taxonomy',
    dimensions:['Achievement','Independence','Recognition','Relationships','Support','Working Conditions'],
    officialUrl:'https://www.onetcenter.org/db_releases.html',
    sourceSystem:'O*NET historical database',
    status:'legacy-reference-only',
    decisionRole:'none-until-revalidated',
    notes:{
      ar:'لا يظهر كملف حديث في O*NET 31.0؛ نحتفظ بالمفاهيم للبحث والمقارنة فقط، ولا نبني عليها scoring إنتاجي.',
      en:'Not present as a current O*NET 31.0 data file; keep the concepts for research/crosswalk purposes only and do not use for production scoring.',
    },
  },
})

export const PSYCHOMETRIC_GOVERNANCE=Object.freeze({
  rules:[
    'No psychometric result may create, delete, or verify academic skill evidence.',
    'No psychometric result may satisfy a formal eligibility gate.',
    'Every observation must retain instrument ID, exact instrument version/adaptation, timestamp, response scale, consent purpose, and provenance.',
    'Raw item responses and derived dimension scores are separate data objects with separate retention controls.',
    'Use-case-specific weights must be learned or governed; never assume equal weights across dimensions or use cases.',
    'Until Saudi validation is complete, results are descriptive tendencies, not Saudi normative percentile claims.',
    'Similarity is not suitability: person-person similarity and person-opportunity fit are separate functions.',
    'A psychometric dimension can contribute to an explanation but must never be the sole reason for a negative recommendation.',
  ],
  prohibitedLabels:['diagnosis','mental fitness','psychological suitability','normal','abnormal','personality pass','personality fail'],
})
