import { useMemo } from 'react'
import { ArrowLeft, ArrowRight, UploadCloud, ShieldCheck, Fingerprint, Waypoints, Route, Check, LockKeyhole, GraduationCap, SearchCheck, FileCheck2 } from 'lucide-react'
import KnowledgeNetwork from './KnowledgeNetwork.jsx'
import { demoCourses } from '../data.js'
import { inferSkills } from '../utils/engine.js'
import { projectStateToPerson360 } from '../ontology/projector.js'
import { buildMatchingProfile, matchTargets } from '../matching/engine.js'
import { trustMicrocopy } from '../content/trustCopy.js'
import { trackPilotEvent } from '../utils/pilotAnalytics.js'
const tr = (lang, ar, en) => lang === 'ar' ? ar : en
export default function LandingExperience({ lang, onTry }) {
  const Arrow = lang === 'ar' ? ArrowLeft : ArrowRight
  const demoMatch = useMemo(() => matchTargets(buildMatchingProfile({ graph: projectStateToPerson360({ state: { courses: demoCourses, approved: true, goal: 'data' }, skills: inferSkills(demoCourses) }) }), { lang }).find(m => m.id === 'job-data-analyst'), [lang])
  const services = [
    [Waypoints, tr(lang, 'افهم شبكة قدراتك', 'Explore your capability network'), tr(lang, 'شاهد كيف يرتبط كل مقرر بقدرة، وكيف تصل هذه القدرة إلى مسار مهني.', 'See how a course connects to a capability, and how that capability connects to a career.')],
    [SearchCheck, tr(lang, 'اسأل: لماذا هذا المسار؟', 'Ask: why this pathway?'), tr(lang, 'مساعد قرار يشرح الدليل والفجوات من ملفك؛ لا تحتاج إلى كتابة سؤال طويل.', 'A decision guide explains your evidence and gaps. Choose a question to get a grounded answer.')],
    [Route, tr(lang, 'حوّل الفجوة إلى خطة', 'Turn a gap into a plan'), tr(lang, 'اختر مسارًا، وحدد ما يحتاج دليلًا، واحصل على خطوات عملية قابلة للمراجعة.', 'Choose a pathway, identify missing evidence and build a practical plan you can review.')],
  ]
  return <div className="landing-v2">
    <section id="home" className="v2-hero">
      <div className="shell v2-hero-grid">
        <div className="v2-hero-copy">
          <span className="v2-eyebrow"><span/>{tr(lang, 'كامن · لطلاب الجامعة والخريجين', 'KAMIN · FOR STUDENTS & GRADUATES')}</span>
          <h1>{tr(lang, 'قدراتك مترابطة.', 'Your skills connect.')}<br/><em>{tr(lang, 'فرصك أوضح.', 'Your next step, clearer.')}</em></h1>
          <p>{tr(lang, 'وراء كل مقرر قدرة. ووراء كل فرصة متطلبات. كامن يربط بينهما، لتعرف ما يناسبك، ولماذا، وما الذي تحتاجه للخطوة القادمة.', 'Behind every course is a capability. Behind every opportunity are requirements. Kamin connects them so you can see what fits, why, and what to work on next.')}</p>
          <div className="v2-actions"><button className="button primary" onClick={onTry}><UploadCloud size={20}/>{tr(lang, 'ابدأ برفع سجلك', 'Start with your transcript')}<Arrow size={18}/></button><a href={`/sample-report.html?lang=${lang}`} onClick={() => trackPilotEvent('sample_report_viewed')}>{tr(lang, 'شاهد تقريرًا تجريبيًا أولًا', 'See a sample report first')}</a></div>
          <div className="v2-trust-inline"><ShieldCheck size={19}/><span>{trustMicrocopy('transcript', lang)}</span></div>
          <div className="v2-entry-note"><span>{tr(lang, 'دون إنشاء حساب', 'No account needed')}</span><span>{tr(lang, 'راجع قبل الاعتماد', 'Review before approval')}</span><span>{tr(lang, 'ملفك تحت سيطرتك', 'You control your profile')}</span></div>
        </div>
        <div className="v2-hero-visual"><KnowledgeNetwork match={demoMatch} lang={lang} goalLabel={tr(lang, 'تحليل البيانات', 'Data analysis')} demo/></div>
      </div>
    </section>
    <section className="v2-value-strip"><div className="shell">{[[FileCheck2, tr(lang, 'سجل تراجعه', 'A record you review')], [Fingerprint, tr(lang, 'قدرات لها مصدر', 'Capabilities with sources')], [Waypoints, tr(lang, 'علاقات تفهمها', 'Connections you understand')], [Route, tr(lang, 'خطوة تعرف سببها', 'A next step with a reason')]].map(([Icon, title], i) => <div key={title}><small>0{i+1}</small><Icon size={20}/><strong>{title}</strong></div>)}</div></section>
    <section id="proof" className="v2-section shell">
      <div className="v2-section-heading"><span className="v2-kicker">{tr(lang, 'من البيانات إلى القرار', 'FROM INFORMATION TO ACTION')}</span><h2>{tr(lang, 'ملف واحد. علاقات تكشف أكثر.', 'One profile. Connections that reveal more.')}</h2><p>{tr(lang, 'خدمات مترابطة تقرأ الأدلة والهدف معًا، وتشرح لك ما تعرفه وما يحتاج معلومات إضافية.', 'Connected services consider your evidence and goal together, explaining what is supported and what still needs information.')}</p></div>
      <div className="v2-services">{services.map(([Icon, title, text], i) => <article key={title}><div className="v2-service-top"><Icon size={26}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><button onClick={onTry}>{tr(lang, 'استكشف الخدمة', 'Explore the service')}<Arrow size={17}/></button></article>)}</div>
      <p className="v2-caption">{tr(lang, 'الخدمات الحالية تعمل محليًا بقواعد وشبكة معرفة تجريبية. المسارات أمثلة مرجعية وليست وظائف شاغرة أو دورات متاحة للحجز.', 'Current services run locally on rules and a pilot knowledge graph. Pathways are reference examples, not vacancies or bookable courses.')}</p>
    </section>
    <section id="person360" className="v2-research-section"><div className="shell v2-research-grid"><div><span className="v2-kicker">{tr(lang, 'الفكرة التي بُني عليها كامن', 'THE IDEA BEHIND KAMIN')}</span><h2>{tr(lang, 'العلاقة تفسّر ما لا تقوله المعلومة وحدها.', 'A connection explains what one fact cannot.')}</h2><p>{tr(lang, 'مستوحى من منهج صاحب المشروع في بحث الدكتوراه: جمع خصائص كيانات متعددة في شبكة دلالية، ثم اكتشاف الروابط بينها. في كامن نطبق هذا النمط على الشخص، وأدلته، وقدراته، ومسارات التعلم والعمل.', 'Inspired by the founder’s doctoral research approach: connecting entities through their properties in a semantic network. Kamin applies that pattern to people, their evidence, capabilities, and learning and career pathways.')}</p><a href={`/methodology.html?lang=${lang}`}>{tr(lang, 'تعرّف على المنهجية وحدودها', 'Read the methodology and its limits')}<Arrow size={17}/></a></div><div className="v2-research-example"><small>{tr(lang, 'مثال يمكن تتبّعه', 'A TRACEABLE EXAMPLE')}</small><div><BookLabel n="01" title={tr(lang, 'مقرر قواعد البيانات', 'Database Systems course')} text="CPIT-260"/><BookLabel n="02" title={tr(lang, 'قدرة في قواعد البيانات', 'Database capability')} text={tr(lang, 'علاقة من خريطة المقررات التجريبية', 'Linked through the pilot course map')}/><BookLabel n="03" title={tr(lang, 'متطلب لمسار تحليل البيانات', 'A requirement for data analysis')} text={tr(lang, 'دليل يدعم الاستكشاف، لا ضمان جاهزية', 'Evidence for exploration, not proof of readiness')}/></div><p>{tr(lang, 'نستعير النمط البحثي؛ صلاحية التوصيات هنا تحتاج تحققًا مستقلًا.', 'The research pattern transfers; the validity of these recommendations still requires separate evaluation.')}</p></div></div></section>
    <section id="how" className="v2-section shell"><div className="v2-section-heading"><span className="v2-kicker">{tr(lang, 'بداية بسيطة', 'A SIMPLE START')}</span><h2>{tr(lang, 'كل معلومة لها فائدة تعود عليك.', 'Every detail should give something back.')}</h2></div><div className="v2-how">{[
      [tr(lang, 'ارفع، ثم راجع', 'Upload, then review'), tr(lang, 'استخرج مقرراتك من PDF أو صورة. صحح الرمز والدرجة قبل بناء أي استنتاج.', 'Extract courses from a PDF or image. Correct codes and grades before any inference.')],
      [tr(lang, 'اختر وجهتك', 'Choose your direction'), tr(lang, 'حدد هدفًا من قائمة واضحة. أضف تفضيلاتك اختيارياً أو اتركها غير محددة.', 'Select a goal from a clear list. Add optional preferences or leave them undecided.')],
      [tr(lang, 'اكتشف السبب والخطوة', 'See why, then act'), tr(lang, 'استكشف الشبكة، افهم نقص الأدلة، وراجع خطة التطوير. احفظ ملفك للعودة إليه.', 'Explore connections, understand evidence gaps and review a development plan. Save your profile to return.')],
    ].map(([title, text], i) => <article key={title}><b>0{i+1}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="trust" className="v2-trust-section"><div className="shell v2-trust-grid"><div><span className="v2-kicker">{tr(lang, 'دقة معلوماتك لمصلحتك', 'ACCURACY WORKS FOR YOU')}</span><h2>{tr(lang, 'ابنِ ملفًا يشبهك، لا إجابة مثالية.', 'Build a profile that reflects you.')}</h2><p>{tr(lang, 'المبالغة قد تقودك إلى مسار يحتاج استعدادًا مختلفًا. الملف الصادق يساعدك على رؤية نقطة البداية، حتى عندما تكون بعض المعلومات غير مكتملة.', 'Overstating experience can point you toward a path requiring different preparation. An honest profile helps you see where to start, even when some details are missing.')}</p><button className="button primary" onClick={onTry}>{tr(lang, 'ابدأ ملفي', 'Build my profile')}<Arrow size={18}/></button></div><div className="v2-trust-promises">{[
      [tr(lang, 'نعطيك السبب قبل أن نسأل', 'A reason for every question'), tr(lang, 'السجل يحدد الأدلة، والهدف يوجّه الاستكشاف. التفضيلات اختيارية.', 'Your record supplies evidence; your goal directs exploration. Preferences are optional.')],
      [tr(lang, '«لم أحدد بعد» إجابة مقبولة', '“Undecided” is a valid answer'), tr(lang, 'لا نكافئ زيادة الادعاءات. المعلومات الناقصة تظهر كحدود، لا كفشل.', 'More claims do not earn rewards. Missing information is a visible limit, not a failure.')],
      [tr(lang, 'تراجع وتصحح وتملك بياناتك', 'Review, correct and own your data'), tr(lang, 'حفظ محلي باختيارك، نسخة احتياطية مشفّرة، وحذف كامل من جهازك.', 'Optional device saving, encrypted backups and complete local deletion.')],
    ].map(([title, text]) => <article key={title}><Check size={19}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <section id="institutions" className="v2-section shell v2-institutions"><div><GraduationCap size={30}/><span className="v2-kicker">{tr(lang, 'للجامعات ومراكز الإرشاد', 'FOR UNIVERSITIES & CAREER CENTERS')}</span><h2>{tr(lang, 'ابدأ جلسة الإرشاد من الدليل.', 'Start the guidance conversation with evidence.')}</h2><p>{tr(lang, 'ملف يستطيع الطالب تفسيره ومراجعته قبل جلسة الإرشاد. كامن يركز على الدليل الجامعي كطبقة مكمّلة لخدمات التوجيه والمهارات الوطنية.', 'Give students a profile they can explain and review before a guidance session. Kamin focuses on academic evidence as a complement to national skills and career services.')}</p></div><div className="v2-institution-links"><a href={`/advisor.html?lang=${lang}`}>{tr(lang, 'عرض المرشد التجريبي', 'Advisor demo')}<Arrow size={18}/></a><a href={`/admin.html?lang=${lang}`}>{tr(lang, 'عرض الإدارة التجريبي', 'Administration demo')}<Arrow size={18}/></a><a href={`/validation.html?lang=${lang}`}>{tr(lang, 'خطة التحقق والتجربة الجامعية', 'Validation and university pilot plan')}<Arrow size={18}/></a><small>{tr(lang, 'العروض ببيانات وهمية. المشاركة المؤسسية غير مفعلة، ولا يوجد تكامل حكومي معلن.', 'Demos use synthetic data. Institutional sharing is not active; no government integration is claimed.')}</small></div></section>
    <section className="v2-faq shell"><h2>{tr(lang, 'قبل أن تبدأ', 'Before you begin')}</h2>{[
      [tr(lang, 'هل يمكنني الاستفادة دون مشاركة بياناتي؟', 'Can I try it without sharing my data?'), tr(lang, 'نعم. افتح التقرير التجريبي أو جرّب المثال داخل التطبيق. عند إدخال سجلك الحقيقي، تتم معالجته محليًا. لا يحتاج الاستخدام إلى حساب.', 'Yes. Open the sample report or try the in-app demo. Your real record is processed locally, and no account is needed.')],
      [tr(lang, 'هل هذه فرص حقيقية ونتائج نهائية؟', 'Are these live opportunities and final assessments?'), tr(lang, 'المسارات والدورات الحالية أمثلة مرجعية. المطابقة استرشادية ولم تُعاير بعد بدراسة مستقلة؛ راجع متطلبات الجهة قبل أي قرار.', 'Current pathways and courses are reference examples. Matching is exploratory and has not been independently calibrated; check provider requirements before deciding.')],
      [tr(lang, 'هل يتأكد كامن أن معلوماتي صحيحة؟', 'Does Kamin verify that my information is true?'), tr(lang, 'يفحص النقص والتكرار وصيغ الدرجات ويطلب مراجعتك. لا يتحقق من أصالة المستند أو من الجامعة، ولا يحوّل إدخالك اليدوي إلى دليل مؤسسي موثق.', 'It checks missing fields, duplicates and grade formats, and asks you to review. It does not authenticate documents or verify them with the university.')],
    ].map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    <section className="v2-final"><div className="shell"><LockKeyhole size={24}/><h2>{tr(lang, 'خطوتك القادمة تبدأ بما تعرفه عن نفسك.', 'Your next step starts with what you know about yourself.')}</h2><button className="button primary" onClick={onTry}>{tr(lang, 'ابدأ برفع سجلك', 'Start with your transcript')}<Arrow size={18}/></button><button className="v2-demo-link" onClick={onTry}>{tr(lang, 'جرّب المثال التوضيحي', 'Try the sample')}</button></div></section>
  </div>
}
function BookLabel({ n, title, text }) { return <div className="v2-chain-item"><b>{n}</b><span><strong>{title}</strong><small>{text}</small></span></div> }
