import {pageHref} from '../../public/site-content.js'
import { useState } from 'react'
import { ChevronDown, ClipboardCheck, ArrowLeft, ArrowRight, UploadCloud, ShieldCheck, Fingerprint, Waypoints, Route, Check, LockKeyhole, GraduationCap, SearchCheck, Compass, Target, Users, BookOpen, MessageSquareText, Search, Network, Terminal }  from 'lucide-react'
import QuickTour from './QuickTour.jsx'
import RelationshipNetwork from './RelationshipNetwork.jsx'
import InferenceDemo from './InferenceExplorer.jsx'
const tr = (lang, ar, en) => lang === 'ar' ? ar : en
export default function LandingExperience({ lang, onTry, onProfile, onKnowledge, onSample }) {
  const [knowledgeSearch,setKnowledgeSearch]=useState('')
  const [dimension,setDimension]=useState(0)
  const dimensions=[
    [Compass,tr(lang,'اهتماماتي','My interests'),tr(lang,'ما تستمتع باستكشافه يشرح ارتباط المسارات بك. لا يتحول إلى مهارة مثبتة.','What you enjoy exploring adds context to pathways; it does not become a proven skill.')],
    [Target,tr(lang,'أهدافي','My goals'),tr(lang,'اتجاه تختاره وتعدّله، يساعدك على التركيز على خطوة تهمك.','A direction you can choose and change, helping you focus on a meaningful next step.')],
    [GraduationCap,tr(lang,'أدلتي','My evidence'),tr(lang,'مقررات تراجعها تربط دراستك بالقدرات ومتطلبات المسار.','Reviewed coursework connects your studies to capabilities and pathway requirements.')],
    [ShieldCheck,tr(lang,'تحكّمي بالبيانات','My data controls'),tr(lang,'كل مصدر اختياري وله غرض واضح. يمكنك التخطي أو الحذف دون ضغط لإكمال الملف.','Each optional source has a clear purpose. Skip or delete information without pressure to complete a profile.')],
  ]
  const Arrow = lang === 'ar' ? ArrowLeft : ArrowRight
  const services = [
    [Waypoints, tr(lang, 'افهم شبكة قدراتك', 'Explore your capability network'), tr(lang, 'اجمع اهتماماتك وأهدافك وتفضيلاتك ودراستك في شبكة واحدة، وافهم دور كل بُعد.', 'Connect your interests, goals, preferences and studies in one network, and understand each dimension.')],
    [SearchCheck, tr(lang, 'اسأل: لماذا هذا المسار؟', 'Ask: why this pathway?'), tr(lang, 'مساعد قرار يشرح الدليل والفجوات من ملفك؛ لا تحتاج إلى كتابة سؤال طويل.', 'A decision guide explains your evidence and gaps. Choose a question to get a grounded answer.')],
    [Route, tr(lang, 'حوّل الفجوة إلى خطة', 'Turn a gap into a plan'), tr(lang, 'اختر مسارًا، وحدد ما يحتاج دليلًا، واحصل على خطوات عملية قابلة للمراجعة.', 'Choose a pathway, identify missing evidence and build a practical plan you can review.')],
  ]
  return <div className="landing-v2 landing-v3">
    <section id="home" className="k-hero">
      <picture className="k-hero-art" aria-hidden="true"><source media="(max-width: 640px)" srcSet="/images/kamin-horizon-mobile.webp"/><img src="/images/kamin-horizon.webp" alt="" width="1792" height="1024" fetchPriority="high" decoding="async"/></picture>
      <div className="shell k-hero-content">
        <span className="k-overline">{tr(lang,'كامن · اكتشف ما يمكن أن تصبحه','KAMIN · DISCOVER WHAT YOU COULD BECOME')}</span>
        <h1>{tr(lang,'افهم قدراتك.','Understand your capabilities.')}<br/><em>{tr(lang,'واكتشف خطوتك القادمة.','Discover your next step.')}</em></h1>
        <p>{tr(lang,'من اهتماماتك إلى أدلتك، ومن دراستك إلى مساراتك. رؤية أوضح لما تملكه، وخطوة عملية لما تريد الوصول إليه.','From your interests to your evidence. From your studies to your possibilities. See what you bring—and choose a practical next step.')}</p>
        <div className="k-hero-actions"><button className="button primary" onClick={onSample}>{tr(lang,'جرّب ببيانات توضيحية','Try with sample data')}</button><button className="button secondary" onClick={onProfile}>{tr(lang,'ابدأ بناء ملفك','Build your profile')}</button></div>
        <div className="k-hero-note"><ShieldCheck size={18}/><span>{tr(lang,'دون حساب. بياناتك تُعالج داخل متصفحك.','No account needed. Your information stays in your browser.')}</span></div>
        <a className="k-hero-report" href={pageHref('sample-report.html',lang)}>{tr(lang,'شاهد تقريرًا تجريبيًا','View a sample report')}</a>
      </div>
      <div className="shell k-hero-bottom"><span>{tr(lang,'قدراتك أوضح. خطوتك أقرب.','CLARITY FOR YOUR NEXT STEP.')}</span><a href="#journey">{tr(lang,'اكتشف التجربة','Discover the experience')}<ChevronDown size={18}/></a></div>
    </section>
    <section id="journey" className="k-journey shell" aria-label={tr(lang,'رحلتك في كامن','Your journey in Kamin')}>
      <div className="k-section-intro"><span className="k-overline">{tr(lang,'طموحك يبدأ بفهمك لنفسك','YOUR AMBITION STARTS WITH UNDERSTANDING YOURSELF')}</span><h2>{tr(lang,'من معرفة نفسك، إلى خطوة تعرف سببها.','From knowing yourself to knowing your next move.')}</h2></div>
      <div className="k-journey-grid">{services.map(([Icon,title,text],i)=><article key={title}><div className="k-journey-top"><span>0{i+1}</span><Icon size={27}/></div><h3>{title}</h3><p>{text}</p></article>)}</div>
    </section>
    <section className="k-preview-section"><div className="shell k-preview-grid"><div className="k-preview-copy"><span className="k-overline">{tr(lang,'تعرّف على كامن في دقيقة','MEET KAMIN IN A MINUTE')}</span><h2>{tr(lang,'شاهد الدليل. افهم العلاقة. اختر خطوتك.','See the evidence. Understand the connection. Choose your step.')}</h2><p>{tr(lang,'جرّب رحلة طالبة افتراضية: من مقرر دراسي، إلى قدرة لها مصدر، ثم مشروع يمكنك تنفيذه ومراجعته.','Follow a fictional student from coursework to a capability with a source, then to a project you can complete and review.')}</p><a href={pageHref('guide.html',lang)}>{tr(lang,'دليلك إلى البداية','Your guide to getting started')}</a><details className="hero-other-start"><summary>{tr(lang,'طرق أخرى للبدء','Other ways to start')}</summary><button className="text-button" onClick={onTry}><UploadCloud size={17}/>{tr(lang,'ابدأ برفع سجلك','Start with your transcript')}</button></details></div><QuickTour lang={lang} onSample={onSample} onProfile={onProfile}/></div></section>
    <section className="pilot-entry shell k-audiences" aria-label={tr(lang,'اختر رحلتك','Choose your journey')}>
      <div className="k-section-intro"><span className="k-overline">{tr(lang,'مساحة لكل طموح','A PLACE FOR EVERY AMBITION')}</span><h2>{tr(lang,'من أين تبدأ؟','Where would you like to start?')}</h2></div>
      <div className="pilot-entry-grid">
        <article><div className="k-audience-icon"><GraduationCap size={32}/></div><small>01</small><h3>{tr(lang,'طالب أو خريج','Student or graduate')}</h3><p>{tr(lang,'افهم ما تدعمه أدلتك، وقارن المسارات، وابنِ مخرجًا يعكس ما تستطيع إنجازه.','Understand what your evidence supports, compare pathways and create work that shows what you can do.')}</p><button className="text-button" onClick={onProfile}>{tr(lang,'ابدأ ملفك','Build your profile')}</button></article>
        <article><div className="k-audience-icon"><Users size={32}/></div><small>02</small><h3>{tr(lang,'مستشار مهني','Career advisor')}</h3><p>{tr(lang,'ابدأ حوار الإرشاد من دليل واضح. استكشف نموذج المراجعة وحدود النسخة الحالية.','Start the guidance conversation with clear evidence. Explore the review model and its current limits.')}</p><a href={pageHref('advisor.html',lang)}>{tr(lang,'استكشف عرضًا وهميًا','Explore a synthetic demo')}</a></article>
        <article><div className="k-audience-icon"><BookOpen size={32}/></div><small>03</small><h3>{tr(lang,'جامعة أو مركز إرشاد','University or career center')}</h3><p>{tr(lang,'شارك في اختبار قيمة كامن، وراجع مقاييس التجربة وخطوات التحقق المؤسسي.','Explore the pilot, its evaluation measures and the path to institutional verification.')}</p><a href={pageHref('business-model.html',lang)}>{tr(lang,'خطة الجامعات والشركاء','Universities & partners')}</a></article>
      </div><p className="v2-caption">{tr(lang,'نسخة بحثية عامة · المسارات استرشادية · المشاركة المؤسسية غير مفعّلة.','Public research release · Exploratory pathways · Institutional sharing is not active.')}</p>
    </section>
    <section id="institutions" className="k-evidence-section"><div className="shell k-evidence-grid"><div><span className="k-overline">{tr(lang,'وضوح يمكنك البناء عليه','CLARITY YOU CAN BUILD ON')}</span><h2>{tr(lang,'طموح تدعمه الأدلة. وقرار يبقى بيدك.','Ambition supported by evidence. Decisions that stay yours.')}</h2><p>{tr(lang,'كل علاقة لها مصدر، وكل توصية لها حدود. راجع ما يعرفه كامن عنك، وصححه، وحدد ما تريد الاحتفاظ به.','Every connection has a source. Every recommendation has limits. Review what Kamin knows about you, correct it and choose what you keep.')}</p><a href={pageHref('trust.html',lang)}>{tr(lang,'استكشف مركز الثقة','Explore the trust center')}</a></div><div className="k-evidence-links"><a href={pageHref('catalog.html',lang)}><BookOpen size={23}/><span><strong>{tr(lang,'المعرفة ومصادرها','Knowledge and its sources')}</strong><small>{tr(lang,'تتبّع المقررات والقدرات والمسارات','Trace courses, capabilities and pathways')}</small></span><Arrow size={20}/></a><button onClick={()=>onKnowledge()}><Network size={23}/><span><strong>{tr(lang,'مستكشف المعرفة ومختبر SPARQL','Knowledge explorer & SPARQL lab')}</strong><small>{tr(lang,'افحص العلاقات واسأل الشبكة','Inspect connections and query the graph')}</small></span><Arrow size={20}/></button><a href={pageHref('validation.html',lang)}><ClipboardCheck size={23}/><span><strong>{tr(lang,'خطة التحقق والتجربة الجامعية','Validation and university pilot plan')}</strong><small>{tr(lang,'أهداف قياس واضحة وحدود معلنة','Clear evaluation goals and stated limits')}</small></span><Arrow size={20}/></a></div></div></section>
    <section id="home-faq" className="v2-faq shell k-faq"><div className="k-section-intro"><span className="k-overline">{tr(lang,'إجابات واضحة','CLEAR ANSWERS')}</span><h2>{tr(lang,'قبل أن تبدأ','Before you begin')}</h2></div>{[
      [tr(lang,'هل يمكنني الاستفادة دون مشاركة بياناتي؟','Can I try it without sharing my data?'),tr(lang,'نعم. افتح التقرير التجريبي أو جرّب المثال داخل التطبيق. عند إدخال سجلك الحقيقي، تتم معالجته محليًا. لا يحتاج الاستخدام إلى حساب.','Yes. Open the sample report or try the in-app demo. Your real record is processed locally, and no account is needed.')],
      [tr(lang,'هل هذه فرص حقيقية ونتائج نهائية؟','Are these live opportunities and final assessments?'),tr(lang,'المسارات والدورات الحالية أمثلة مرجعية. المطابقة استرشادية ولم تُعاير بعد بدراسة مستقلة؛ راجع متطلبات الجهة قبل أي قرار.','Current pathways and courses are reference examples. Matching is exploratory and has not been independently calibrated; check provider requirements before deciding.')],
      [tr(lang,'هل يتأكد كامن أن معلوماتي صحيحة؟','Does Kamin verify that my information is true?'),tr(lang,'يفحص النقص والتكرار وصيغ الدرجات ويطلب مراجعتك. لا يتحقق من أصالة السجل مع الجامعة. استيراد الاعتمادات متاح، لكن سجل جهات الإصدار الموثوقة ما زال فارغًا.','It checks missing fields, duplicates and grade formats, and asks you to review. It does not authenticate transcripts with the university. Credential import is available, but the trusted-issuer registry is still empty.')],
    ].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    <details className="pilot-advanced shell"><summary>{tr(lang,'للاستكشاف المتقدم: الشبكة والمنهجية والاستدلال','Explore further: network, methodology and inference')}</summary>
      <RelationshipNetwork lang={lang} demo onKnowledge={()=>onKnowledge()}/>
    <section className="knowledge-gateway shell" id="profile-dimensions">
      <div className="knowledge-gateway-top"><div><span className="v2-kicker">{tr(lang,'اكتشف قبل أن تشارك','EXPLORE BEFORE YOU SHARE')}</span><h2>{tr(lang,'ما الذي تريد فهمه؟','What would you like to understand?')}</h2><p>{tr(lang,'استكشف القدرات والاهتمامات والمسارات دون إدخال بيانات شخصية.','Explore capabilities, interests and pathways without entering personal information.')}</p></div><Network size={34}/></div>
      <form className="knowledge-home-search" onSubmit={e=>{e.preventDefault();onKnowledge(knowledgeSearch)}}><label className="sr-only" htmlFor="knowledge-home-search">{tr(lang,'ابحث في المعرفة المرجعية','Search reference knowledge')}</label><Search size={21}/><input id="knowledge-home-search" type="search" value={knowledgeSearch} onChange={e=>setKnowledgeSearch(e.target.value)} placeholder={tr(lang,'قدرة، اهتمام، أو مسار… مثل قواعد البيانات','Capability, interest, or pathway… e.g. databases')}/><button className="button primary" type="submit">{tr(lang,'استكشف','Explore')}<Arrow size={17}/></button></form>
      <div className="profile-ribbon" aria-label={tr(lang,'أبعاد ملفك','Your profile dimensions')}>{dimensions.map(([Icon,label],i)=><button key={label} aria-pressed={dimension===i} onClick={()=>setDimension(i)}><Icon size={22}/>{label}</button>)}</div><p className="profile-ribbon-detail" aria-live="polite">{dimensions[dimension][2]}</p>
    </section>
    <section id="proof" className="v2-section shell">
      <div className="v2-section-heading"><span className="v2-kicker">{tr(lang, 'من البيانات إلى القرار', 'FROM INFORMATION TO ACTION')}</span><h2>{tr(lang, 'ملف واحد. علاقات تكشف أكثر.', 'One profile. Connections that reveal more.')}</h2><p>{tr(lang, 'تبدأ من صورة عنك، ثم تربط ما تعرفه وما تفضّله بالمسارات الممكنة.', 'Start with a picture of yourself, then connect what you know and prefer to possible pathways.')}</p></div>
      <div className="v2-services">{services.map(([Icon, title, text], i) => <article key={title}><div className="v2-service-top"><span className="service-icon"><Icon size={30}/></span><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><button onClick={onProfile}>{tr(lang, 'استكشف الخدمة', 'Explore the service')}<Arrow size={17}/></button></article>)}</div>
      <p className="v2-caption">{tr(lang, 'تعمل الخدمات محليًا: شبكة تفسّر العلاقات، واكتشاف اختياري للمسارات من اهتمام تكتبه بكلماتك. المسارات أمثلة مرجعية وليست وظائف شاغرة أو دورات للحجز.', 'Services run locally: a graph explains connections, and optional discovery explores pathways from interests in your own words. Pathways are reference examples, not vacancies or bookable courses.')}</p>
    </section>
    <section id="person360" className="v2-research-section"><div className="shell v2-research-grid"><div><span className="v2-kicker">{tr(lang, 'الفكرة التي بُني عليها كامن', 'THE IDEA BEHIND KAMIN')}</span><h2>{tr(lang, 'العلاقة تفسّر ما لا تقوله المعلومة وحدها.', 'A connection explains what one fact cannot.')}</h2><p>{tr(lang, 'مستوحى من منهج صاحب المشروع في بحث الدكتوراه: جمع خصائص كيانات متعددة في شبكة دلالية، ثم اكتشاف الروابط بينها. في كامن نطبق هذا النمط على الشخص، وأدلته، وقدراته، ومسارات التعلم والعمل.', 'Inspired by the founder’s doctoral research approach: connecting entities through their properties in a semantic network. Kamin applies that pattern to people, their evidence, capabilities, and learning and career pathways.')}</p><a href={pageHref('methodology.html',lang)}>{tr(lang, 'تعرّف على المنهجية وحدودها', 'Read the methodology and its limits')}<Arrow size={17}/></a></div><div className="v2-research-example"><small>{tr(lang, 'مثال يمكن تتبّعه', 'A TRACEABLE EXAMPLE')}</small><div><BookLabel n="01" title={tr(lang, 'مقرر قواعد البيانات', 'Database Systems course')} text="CPIT-260"/><BookLabel n="02" title={tr(lang, 'قدرة في قواعد البيانات', 'Database capability')} text={tr(lang, 'علاقة من خريطة المقررات التجريبية', 'Linked through the pilot course map')}/><BookLabel n="03" title={tr(lang, 'متطلب لمسار تحليل البيانات', 'A requirement for data analysis')} text={tr(lang, 'دليل يدعم الاستكشاف، لا ضمان جاهزية', 'Evidence for exploration, not proof of readiness')}/></div><p>{tr(lang, 'نستعير النمط البحثي؛ صلاحية التوصيات هنا تحتاج تحققًا مستقلًا.', 'The research pattern transfers; the validity of these recommendations still requires separate evaluation.')}</p></div></div></section>
    <section id="how" className="v2-section shell"><div className="v2-section-heading"><span className="v2-kicker">{tr(lang, 'بداية بسيطة', 'A SIMPLE START')}</span><h2>{tr(lang, 'كل معلومة لها فائدة تعود عليك.', 'Every detail should give something back.')}</h2></div><div className="v2-how">{[
      [tr(lang, 'ابدأ بما يشبهك', 'Start with what reflects you'), tr(lang, 'اختر اهتمامك وهدفك وتفضيلاتك من قوائم بسيطة؛ لا توجد إجابة مثالية.', 'Choose interests, a goal and preferences from simple lists. There is no perfect answer.')],
      [tr(lang, 'أضف دليلًا عندما تكون مستعدًا', 'Add evidence when ready'), tr(lang, 'أضف سجلك الأكاديمي وراجع استخراج المقررات لتربط دراستك بقدرات لها مصدر.', 'Add your transcript and review extracted courses to connect your studies to capabilities with sources.')],
      [tr(lang, 'اكتشف السبب والخطوة', 'See why, then act'), tr(lang, 'استكشف الشبكة، افهم نقص الأدلة، وراجع خطة التطوير. احفظ ملفك للعودة إليه.', 'Explore connections, understand evidence gaps and review a development plan. Save your profile to return.')],
    ].map(([title, text], i) => <article key={title}><b>0{i+1}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="trust" className="v2-trust-section"><div className="shell v2-trust-grid"><div><span className="v2-kicker">{tr(lang, 'دقة معلوماتك لمصلحتك', 'ACCURACY WORKS FOR YOU')}</span><h2>{tr(lang, 'ابنِ ملفًا يشبهك، لا إجابة مثالية.', 'Build a profile that reflects you.')}</h2><p>{tr(lang, 'المبالغة قد تقودك إلى مسار يحتاج استعدادًا مختلفًا. الملف الصادق يساعدك على رؤية نقطة البداية، حتى عندما تكون بعض المعلومات غير مكتملة.', 'Overstating experience can point you toward a path requiring different preparation. An honest profile helps you see where to start, even when some details are missing.')}</p><button className="button primary" onClick={onProfile}>{tr(lang, 'ابدأ ملفي', 'Build my profile')}<Arrow size={18}/></button></div><div className="v2-trust-promises">{[
      [tr(lang, 'نعطيك السبب قبل أن نسأل', 'A reason for every question'), tr(lang, 'الاهتمامات تضيف سياقًا، والهدف يوجّه الاستكشاف، والسجل يدعم الأدلة. تختار ما تضيفه.', 'Interests add context, goals guide exploration and transcripts support evidence. You choose what to add.')],
      [tr(lang, '«لم أحدد بعد» إجابة مقبولة', '“Undecided” is a valid answer'), tr(lang, 'لا نكافئ زيادة الادعاءات. المعلومات الناقصة تظهر كحدود، لا كفشل.', 'More claims do not earn rewards. Missing information is a visible limit, not a failure.')],
      [tr(lang, 'تراجع وتصحح وتملك بياناتك', 'Review, correct and own your data'), tr(lang, 'حفظ محلي باختيارك، نسخة احتياطية مشفّرة، وحذف كامل من جهازك.', 'Optional device saving, encrypted backups and complete local deletion.')],
    ].map(([title, text]) => <article key={title}><Check size={19}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <InferenceDemo lang={lang}/>
      <a href={pageHref('faq.html',lang)}>{tr(lang,'جميع الأسئلة الشائعة','All frequently asked questions')}</a>
    </details>
    <section className="v2-final k-final"><div className="shell"><span className="k-overline">{tr(lang,'ابدأ من حيث أنت','START WHERE YOU ARE')}</span><h2>{tr(lang,'خطوتك القادمة،\nأقرب مما تتصور.','Your next step.\nCloser than you think.')}</h2><button className="button primary" onClick={onProfile}>{tr(lang,'ابدأ بناء ملفك','Build your profile')}</button><button className="v2-demo-link" onClick={onTry}>{tr(lang,'افتح مساحة العمل','Open workspace')}</button></div></section>
  </div>
}
function BookLabel({ n, title, text }) { return <div className="v2-chain-item"><b>{n}</b><span><strong>{title}</strong><small>{text}</small></span></div> }
