const section=(title,body)=>`<section class="k-doc-card"><h2>${title}</h2>${body}</section>`
const list=items=>`<ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul>`
const repo='https://github.com/adeebnoor/KAMIN/blob/main/docs/'
function nativePlan(lang){
 const ar=lang==='ar'
 return section(ar?'من نموذج أولي إلى منتج AI-Native':'From a prototype to an AI-native product',
 `<p>${ar?'خط البداية يتضمن الآن ست مهام تطبيقية وتقدمًا محفوظًا ومراجعة محلية، ومقارنة مسارات، واقتراح قدرات من وصف المشروع، واستيراد اعتماد ضمن حدود معلنة. هذه وظائف موروثة؛ يسجل الفريق إضافاته منفصلة.':'The baseline now includes six practical tasks, saved progress and local reviews, pathway comparison, project capability suggestions and bounded credential import. These are inherited features; record new contributions separately.'}</p>`+
 list(ar?[
 'قسّموا العمل إلى وحدات مستقلة بعقود واضحة: الهدف، المدخلات والمخرجات، الحدود ومعيار القبول قبل التنفيذ.',
 'لكل تغيير فرع ومراجع بشري مختلف، ودليل يمكن إعادة تشغيله، وخطة رجوع. استخدموا الوكلاء للتنفيذ والاختبار مع مسؤولية بشرية مسمّاة.',
 'ابنوا شريحة متكاملة في بيئة اختبار ببيانات وهمية: هوية وصلاحيات، API، قاعدة بيانات وتخزين اختياري بموافقة مستقلة. هذه خدمات مخططة وليست مفعلة في النسخة العامة.',
 'الاستضافة الحالية على Render فعلية؛ المطلوب التالي نطاق معتمد، بيئتا اختبار وإنتاج، مراقبة، نسخ واستعادة، ومالك للتشغيل.',
 'اختبروا عزل المستخدمين، وسحب المشاركة، والادعاء غير المسند وحقن التعليمات. قيسوا وقت القبول أو الرفض بثقة، والأخطاء المؤكدة التي تعبر المراجعة.'
 ]:[
 'Divide work into isolated units with an outcome, inputs/outputs, constraints and acceptance criteria written before implementation.',
 'Every change has a branch, a different human reviewer, reproducible evidence and rollback. Agents support execution and testing; a named human remains accountable.',
 'Build one vertical slice on staging with synthetic data: identity and permissions, an API, a database and separately consented optional storage. These services are planned, not active in the public release.',
 'The Render static site is real hosting. Next: an approved domain, staging/production separation, monitoring, backup restoration and an operational owner.',
 'Challenge user isolation, sharing withdrawal, unsupported claims and prompt injection. Measure time to informed acceptance/rejection and confirmed defects escaping review.'
 ])+`<p><a href="${repo}AI_NATIVE_PRODUCT_PLAN.md">${ar?'خطة التحول إلى منتج AI-Native':'AI-native product delivery plan'}</a> · <a href="${repo}TASK_CONTRACT_TEMPLATE.md">${ar?'قالب عقد المهمة ودليل القبول':'Task contract and acceptance evidence template'}</a></p>`)
}
export function capstonePage(lang){
 if(lang==='ar')return ['خطة فريق كامن','ثلاثة طلاب، منتج قابل للاستخدام بنهاية الفصل، وعشرة أشهر للتطوير والتقييم تحت إشراف أ.د. أديب نور.',
 section('ما الذي نبدأ منه؟','<p>النسخة الحالية تتضمن ملفًا محليًا، مراجعة السجل، شبكة معرفة واستدلالًا مفسّرًا، SPARQL وتصدير RDF وCSV، واكتشافًا دلاليًا اختياريًا داخل المتصفح ولقطة قدرات مشفرة. أضيفت جولة بداية قصيرة، وكتالوج يضم 9 مسارات مهنية و10 مسارات تدريب وتطبيق، وخطة تحقق مؤسسي وميداني مقترحة. يسجّل الفريق إصدار البداية ثم يوضح مساهماته الجديدة. التجربة الميدانية في ثلاث كليات هدف مخطط؛ لم نعلن نتائج لها.</p>')+
 nativePlan('ar')+
 section('مسؤوليات القيادة',list(['الطالب الأول: رحلة الطالب، العربية والإنجليزية، الجوال وإمكانية الوصول، دليل الاستخدام والنشر.','الطالب الثاني: RDF والأنطولوجيا، مصادر العلاقات والقواعد، أسئلة SPARQL، والتحقق بـSHACL.','الطالب الثالث: تقييم الاسترجاع الدلالي وتحسينه، خدمة توصية واحدة مفسّرة، خطوط الأساس واختبارات جودة البيانات.'])+'<p>الاختبار والخصوصية والتكامل مسؤولية الجميع. لكل تغيير منفذ ومراجع من طالب آخر.</p>')+
 section('أول أسبوعين',list(['تشغيل المشروع لدى الأعضاء الثلاثة وتسجيل إصدار البداية ونتيجة الاختبارات.','تجربة ست مهام: ملف دون سجل، مراجعة دليل وهمي، فهم التوصية، الحفظ والاستعادة، الحذف، واستعلام الشبكة.','تقديم عشرة تحسينات مرتبة ومعيار قبول لكل منها، وعشرة أسئلة كفاءة بإجابات متوقعة.','تعديل صغير لكل طالب عبر Pull Request ومراجعة زميل، ثم عرض حي.','بدء تنسيق الكليات الثلاث ومديرَي الموارد البشرية الذين يستطيع المشرف توصيل الفريق بهما. لا يُعد ذلك اتفاق مشاركة مؤكدًا.']))+
 section('بوابة نهاية الفصل',list(['الأسابيع 1–4: خط بداية موثق، بروتوكول وتنسيق مبكر، وتغطية مرجعية محدودة لكل كلية.','الأسابيع 5–7: خدمة توصية متكاملة، مقارنة بخط أساس، وتحقق من الأدلة والموافقة.','الأسابيع 8–9: إصدار تجريبي منشور، نطاق رسمي بعد اختياره واعتماده، واختبار الاستعادة والرجوع لإصدار سابق.','الأسابيع 10–12: تجربة مع ثلاث كليات بعد الاعتماد، ثم إصلاحات موثقة.','الأسابيع 13–14: منتج عامل، دليل، تقرير مجمع وحدود معلنة، وفيديو وتسليم تشغيلي.'])+'<p>هذا نموذج من 14 أسبوعًا؛ تثبت التواريخ وفق التقويم الجامعي. الأشهر المتبقية حتى الشهر العاشر للتوسع والتقييم والتحسين والتسليم البحثي. إذا تأخر اعتماد الدراسة، يظهر ذلك بوضوح ولا تُعرض البيانات الوهمية باعتبارها نتائج ميدانية.</p>')+
 section('ما الإضافة في الذكاء الاصطناعي؟','<p>ابدؤوا من نموذج التضمين المحلي الموجود: قارنوه بالكلمات المفتاحية، ثم اختبروا التحسين مع أدلة الشبكة. الهدف استرجاع مسار مفيد وشرح مصدره وحدوده. يمكن تطوير استخراج منظم لوصف مشروع أو مساعد GraphRAG بعد نجاح تجربة محدودة ومراجعة تدفق البيانات؛ لا يلزم تنفيذ كل التقنيات لإطلاق المنتج.</p>')+
 section('تجربة ثلاث كليات ومراجعة الموارد البشرية','<p>هدف تجنيد استكشافي مقترح: 20 مشاركًا لكل كلية بعد اعتماد البروتوكول والجدوى، وليس حجم عينة مثبتًا لاختبار تفوق. نقيس إنجاز المهام والوقت والأخطاء وفهم التوصية وراحة الإفصاح، ونقيّم الاسترجاع بالعربية والإنجليزية على مجموعة اختبار ثابتة. يراجع خبيران من الموارد البشرية أمثلة وهمية وجودة الشرح إذا تأكدت مشاركتهما؛ لا تتاح لهما ملفات الطلاب تلقائيًا.</p><p>تُنشر النتائج المجمعة والقيود وإصدار النظام فقط بعد تنفيذ الدراسة، مع فصلها حسب التخصص عندما يسمح حجم المجموعة بحماية المشاركين.</p>')+
 section('ملفات العمل والاجتماعات',`<p>اجتماع أسبوعي 30–45 دقيقة وعرض متكامل كل أسبوعين. التقييم على المشكلة والتنفيذ ودليل الاختبار والنتائج القابلة لإعادة الإنتاج.</p><p><a href="${repo}CAPSTONE_ROADMAP_20260927.md">الخطة التفصيلية</a> · <a href="${repo}KICKOFF_TASKS.csv">مهام أول أسبوعين</a> · <a href="${repo}PILOT_PROTOCOL_DRAFT.md">مسودة بروتوكول التقييم</a> · <a href="/validation.html">حالة التحقق</a></p><p>البدء ببيانات وهمية؛ البيانات الصحية والمالية والمخالفات وتحليل الشخصية من حسابات الطلاب خارج نطاق العمل. أي دراسة بمشاركين أو تخزين مركزي أو إرسال لمزود نموذج خارجي يمر بمراجعة واعتماد مناسبين قبل تفعيله.</p>`)]
 return ['Kamin capstone team plan','Three students, a usable product by the end of the semester, and ten months of development and evaluation supervised by Prof. Adeeb Noor.',
 section('Starting point','<p>The baseline includes a local profile, transcript review, an explainable knowledge graph, SPARQL, RDF/CSV exports, optional browser-based semantic recall and encrypted capability snapshots. The baseline also includes a short starter tour, 9 career and 10 practice pathways, and a proposed institutional and field-validation roadmap. Record the starting release and distinguish new student contributions. The three-college field study is planned; no field results are claimed.</p>')+
 nativePlan('en')+
 section('Leadership responsibilities',list(['Student 1: student journeys, Arabic/English, mobile, accessibility, user guidance and deployment.','Student 2: ontology and RDF, sourced relationships and rules, SPARQL competency questions and SHACL validation.','Student 3: evaluate and improve local semantic recall, deliver one explainable recommendation service, baselines and data-quality tests.'])+'<p>Integration, testing and privacy belong to everyone. Every change has an implementer and a peer reviewer.</p>')+
 section('First two weeks',list(['Run the project on all three machines; record the starting commit and test results.','Exercise six tasks: profile without a transcript, synthetic evidence review, recommendation explanation, save/restore, deletion and graph query.','Prioritize ten improvements with acceptance criteria and ten competency questions with expected answers.','Submit one small peer-reviewed pull request per student and present a live team demo.','Start coordination with three colleges and two HR managers the supervisor can introduce. Participation is not yet confirmed.']))+
 section('End-of-semester release gate',list(['Weeks 1–4: baseline, early protocol review and coordination, limited sourced coverage for each college.','Weeks 5–7: one complete recommendation service, baseline comparison, evidence and consent checks.','Weeks 8–9: published pilot release, a selected and approved project domain, restore and rollback checks.','Weeks 10–12: approved three-college field study and documented fixes.','Weeks 13–14: working release, guide, aggregate findings and limits, demo video and operational handover.'])+'<p>This is a 14-week template; dates follow the university calendar. Remaining months through month ten cover improvement, expansion and research evaluation. If approvals are delayed, report the field study as incomplete rather than treating synthetic examples as field evidence.</p>')+
 section('The AI contribution','<p>Start with the existing local embedding model: compare it with keywords, then evaluate improvements using graph evidence. Retrieve useful pathways and explain their sources and limits. Structured project-description extraction or a GraphRAG assistant can follow a bounded evaluation and data-flow review. Shipping the product does not require every proposed technique.</p>')+
 section('Three colleges and HR review','<p>Proposed exploratory recruitment target: 20 participants per college, subject to protocol approval and feasibility, not a powered superiority sample. Measure task completion, time, errors, explanation comprehension and disclosure comfort; evaluate Arabic/English retrieval on a frozen test set. Two HR experts may review synthetic scenarios and explanations once participation is confirmed; student profiles are not automatically shared.</p><p>Publish aggregate results, limitations and the tested release only after running the study. Break down findings by discipline only where group sizes protect participants.</p>')+
 section('Working files and meetings',`<p>Meet weekly for 30–45 minutes and demonstrate an integrated release every two weeks. Assessment covers the problem, implementation, test evidence and reproducible results.</p><p><a href="${repo}CAPSTONE_ROADMAP_20260927.md">Detailed roadmap</a> · <a href="${repo}KICKOFF_TASKS.csv">First-two-week task board</a> · <a href="${repo}PILOT_PROTOCOL_DRAFT.md">Draft evaluation protocol</a> · <a href="/validation.html">Validation status</a></p><p>Begin with synthetic data. Health, financial and violation records and personality inference from student accounts are outside scope. Participant research, central storage and external model processing require appropriate review and approval before activation.</p>`)]
}
