import {targetProfiles,TARGET_CATALOG_VERSION} from '../src/matching/targets.js'
import {skills,courseSkillMap} from '../src/data.js'
import {relationGovernance,mappingGovernance,governanceLine,TAXONOMY_ROLES} from '../src/catalog/governance.js'
import {opportunityStatus} from '../src/market/localOpportunities.js'
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')
const labels=new Map(Object.values(skills).map(s=>[s.id,s.labels]))
for(const [id,ar,en] of [['sql','استعلامات SQL','SQL'],['python','التحليل باستخدام Python','Python'],['data-visualization','عرض البيانات بصريًا','Data visualization'],['power-bi','لوحات Power BI','Power BI']])labels.set(id,{ar,en})
export function catalogPage(lang){
 const t=(ar,en)=>lang==='ar'?ar:en
 const list=(ids=[])=>ids.map(id=>esc(labels.get(id)?.[lang]||id)).join(' · ')||t('لا توجد متطلبات أولية في المثال','No prerequisites in this example')
 const rows=type=>targetProfiles.filter(x=>x.type===type).map(x=>`<article class="k-doc-card" id="${x.id}"><h3>${esc(x.title[lang])}</h3><p>${esc(x.outcome[lang])}</p><p><strong>${t('قدرات للاستكشاف','Capabilities for exploration')}:</strong> ${list(type==='job'?x.requiredSkills:x.teachesSkills)}</p><p><a href="${esc(x.source.url)}">${esc(x.source.title)}</a> · ${t('مراجعة المرجع','Reference checked')}: ${x.source.checked}</p><p class="k-governance">${esc(governanceLine(relationGovernance(x),lang))}</p><small>${t('ربط تجريبي من كامن؛ ليس تحققًا مؤسسيًا أو حصرًا كاملًا لمتطلبات المهنة.','Kamin pilot mapping; not institutional verification or a complete occupational requirement set.')}</small></article>`).join('')
 const mappings=Object.keys(courseSkillMap).map(code=>{const g=mappingGovernance(code);return `<li><strong>${esc(code)}</strong> → ${list(g.skills)} · ${esc(governanceLine(g,lang))}</li>`}).join('')
 const opportunities=opportunityStatus()
 return [t('الكتالوج ومصادره','Catalog & sources'),t('مسارات محددة ومصادر قابلة للمراجعة، مع إبقاء حدود كل علاقة ظاهرة.','Defined pathways with reviewable sources and visible limits for each mapping.'),
 `<section class="k-doc-card"><h2>${t('نطاق هذه النسخة','Scope of this release')}</h2><p>${targetProfiles.filter(x=>x.type==='job').length} ${t('مسارات مهنية','career pathways')} · ${targetProfiles.filter(x=>x.type==='training').length} ${t('مسارات تدريب وتطبيق','training and practice pathways')}</p><p>${t('نطاق أولي للحوسبة وتقنية المعلومات. المراجع المهنية الدولية تصف السياق ولا تثبت الطلب السعودي أو تكافؤ التصنيفات. مقترحات التدريب أنشطة تعليمية من كامن، وليست دورات متاحة للحجز.','An initial computing and IT scope. International references describe occupational context, not Saudi demand or taxonomy equivalence. Training proposals are Kamin learning activities, not bookable courses.')}</p><code>${TARGET_CATALOG_VERSION}</code></section>
 <section class="k-doc-card"><h2>${t('كيف نوسع الكتالوج؟','How we expand coverage')}</h2><p>${t('لكل إضافة: مصدر ونطاق وتاريخ مراجعة، ثم مراجعة مختص للمتطلبات وأمثلة صحيحة وخاطئة. نراجع الروابط كل ثلاثة أشهر كهدف حوكمة مقترح؛ لا يُضاف ربط مقرر بقدرة دون اعتماد منفصل.','Each addition needs a source, scope and review date, followed by a specialist review of requirements and positive and negative examples. A proposed governance target is quarterly link review; course-to-capability mappings need separate approval.')}</p><a href="/validation.html">${t('جدول التحقق المقترح','Proposed validation schedule')}</a></section>
 <section class="k-doc-card" id="governance"><h2>${t('حوكمة كل علاقة','Governance of every relation')}</h2><p>${t('لكل علاقة في الكتالوج: مصدر، وإصدار، وتاريخ مراجعة، ومالك للمراجعة، ونطاق صلاحية. لا تُنشر علاقة تنقصها إحدى هذه الخمس، ولا تنتج مهارة مثبتة من تشابه نصي وحده. خريطة مقررات CPIT لا تُعمَّم على برامج أخرى.','Every relation in the catalog carries a source, a version, a review date, a review owner and a validity scope. A relation missing any of the five is not published, and no verified skill ever results from text similarity alone. The CPIT course map is not generalised to other programmes.')}</p><ul><li><strong>ESCO</strong> · ${esc(TAXONOMY_ROLES.esco[lang])}</li><li><strong>O*NET</strong> · ${esc(TAXONOMY_ROLES.onet[lang])}</li><li><strong>SSCO</strong> · ${esc(TAXONOMY_ROLES.ssco[lang])}</li></ul><h3>${t('روابط المقررات بالقدرات','Course-to-capability mappings')}</h3><ul>${mappings}</ul></section>
 <section class="k-doc-card" id="local-opportunities"><h2>${t('فرص محلية','Local opportunities')}</h2><p>${esc(opportunities.note[lang])}</p><code>${opportunities.schemaVersion} · ${t('محمّل','loaded')}: ${opportunities.loaded}</code></section>
 <h2>${t('المسارات المهنية','Career pathways')}</h2>${rows('job')}<h2>${t('التدريب والتطبيق','Training and practice')}</h2>${rows('training')}`]
}
