import {targetProfiles,TARGET_CATALOG_VERSION} from '../src/matching/targets.js'
import {skills} from '../src/data.js'
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')
const labels=new Map(Object.values(skills).map(s=>[s.id,s.labels]))
for(const [id,ar,en] of [['sql','استعلامات SQL','SQL'],['python','التحليل باستخدام Python','Python'],['data-visualization','عرض البيانات بصريًا','Data visualization'],['power-bi','لوحات Power BI','Power BI']])labels.set(id,{ar,en})
export function catalogPage(lang){
 const t=(ar,en)=>lang==='ar'?ar:en
 const list=(ids=[])=>ids.map(id=>esc(labels.get(id)?.[lang]||id)).join(' · ')||t('لا توجد متطلبات أولية في المثال','No prerequisites in this example')
 const rows=type=>targetProfiles.filter(x=>x.type===type).map(x=>`<article class="k-doc-card" id="${x.id}"><h3>${esc(x.title[lang])}</h3><p>${esc(x.outcome[lang])}</p><p><strong>${t('قدرات للاستكشاف','Capabilities for exploration')}:</strong> ${list(type==='job'?x.requiredSkills:x.teachesSkills)}</p><p><a href="${esc(x.source.url)}">${esc(x.source.title)}</a> · ${t('مراجعة المرجع','Reference checked')}: ${x.source.checked}</p><small>${t('ربط تجريبي من كامن؛ ليس تحققًا مؤسسيًا أو حصرًا كاملًا لمتطلبات المهنة.','Kamin pilot mapping; not institutional verification or a complete occupational requirement set.')}</small></article>`).join('')
 return [t('الكتالوج ومصادره','Catalog & sources'),t('مسارات محددة ومصادر قابلة للمراجعة، مع إبقاء حدود كل علاقة ظاهرة.','Defined pathways with reviewable sources and visible limits for each mapping.'),
 `<section class="k-doc-card"><h2>${t('نطاق هذه النسخة','Scope of this release')}</h2><p>${targetProfiles.filter(x=>x.type==='job').length} ${t('مسارات مهنية','career pathways')} · ${targetProfiles.filter(x=>x.type==='training').length} ${t('مسارات تدريب وتطبيق','training and practice pathways')}</p><p>${t('نطاق أولي للحوسبة وتقنية المعلومات. المراجع المهنية الدولية تصف السياق ولا تثبت الطلب السعودي أو تكافؤ التصنيفات. مقترحات التدريب أنشطة تعليمية من كامن، وليست دورات متاحة للحجز.','An initial computing and IT scope. International references describe occupational context, not Saudi demand or taxonomy equivalence. Training proposals are Kamin learning activities, not bookable courses.')}</p><code>${TARGET_CATALOG_VERSION}</code></section>
 <section class="k-doc-card"><h2>${t('كيف نوسع الكتالوج؟','How we expand coverage')}</h2><p>${t('لكل إضافة: مصدر ونطاق وتاريخ مراجعة، ثم مراجعة مختص للمتطلبات وأمثلة صحيحة وخاطئة. نراجع الروابط كل ثلاثة أشهر كهدف حوكمة مقترح؛ لا يُضاف ربط مقرر بقدرة دون اعتماد منفصل.','Each addition needs a source, scope and review date, followed by a specialist review of requirements and positive and negative examples. A proposed governance target is quarterly link review; course-to-capability mappings need separate approval.')}</p><a href="/validation.html">${t('جدول التحقق المقترح','Proposed validation schedule')}</a></section>
 <h2>${t('المسارات المهنية','Career pathways')}</h2>${rows('job')}<h2>${t('التدريب والتطبيق','Training and practice')}</h2>${rows('training')}`]
}
