// Engineering mapping reviewed against the official PDPL on 30 Sep 2026.
// DPV terms classify the mapping; they are not statutory equivalences or a
// claim that complete DPV consent receipts are emitted by the current app.
export const PDPL_SOURCE='https://dgp.sdaia.gov.sa/wps/portal/pdp/knowledgecenter/details/PDPL'
export const DPV_SOURCE='https://www.w3.org/community/reports/dpvcg/CG-FINAL-dpv-20240801/'
const rows=[
 ['4, 21','DataSubject','الحقوق والوصول والتصحيح','Rights, access and correction','جزئي','Partial','عرض الملف، مراجعة السجل، تصدير واستعادة محليان وحذف من المتصفح.','Profile view, transcript review, local export/restore and browser deletion.','تسمية جهة التحكم وقناة حقوق رسمية وإجراءات الاستجابة.','Name a controller and a formal rights channel and response process.'],
 ['5, 7','Consent','الموافقة وسحبها','Consent and withdrawal','مطبق محليًا','Implemented locally','أذونات منفصلة للسجل والاهتمامات؛ المعالجة الاختيارية لا تبدأ تلقائيًا.','Separate transcript and interest permissions; optional processing does not start automatically.','تقييم المسوغ والأهلية وإجراءات الموافقة المؤسسية.','Assess lawful basis, capacity and institutional consent procedures.'],
 ['10, 11','Purpose','الغرض والحد الأدنى','Purpose and minimisation','مطبق محليًا','Implemented locally','مدخلات يختارها الطالب؛ اللقطة تشارك القدرات المختارة فقط؛ لا جمع لحسابات اجتماعية.','Student-chosen inputs; snapshots share selected capabilities only; no social-account collection.','توثيق الضرورة لكل حقل في أي تكامل جديد.','Document necessity for each field in any new integration.'],
 ['12, 13','DataController','الإشعار والهوية','Notice and identity','جزئي','Partial','سياسة خصوصية، توضيح معالجة المتصفح، مشرف المشروع وقناة التواصل.','Privacy notice, browser-processing explanation, project supervisor and contact route.','هوية وعنوان جهة التحكم المؤسسية وإشعارها المعتمد غير محددين بعد.','An institutional controller’s identity, address and approved notice are not yet designated.'],
 ['14, 17','Processing','الدقة والتحديث','Accuracy and updates','جزئي','Partial','يراجع الطالب الأدلة قبل اعتمادها؛ يعاد حساب المخرجات بعد التعديل والسحب.','Students review evidence before approval; outputs recompute after edits and withdrawal.','لا تحقق من الجهة المصدرة؛ تحديث نسخ المستلمين يحتاج إجراءً منفصلًا.','No issuer verification; updating recipient copies needs a separate process.'],
 ['18','Processing','الاحتفاظ والإتلاف','Retention and destruction','جزئي','Partial','جلسة مؤقتة أو حفظ محلي باختيار الطالب؛ أزرار سحب وحذف.','Temporary session or opt-in local saving; withdrawal and deletion controls.','حذف الجهاز لا يمحو الملفات المنزلة أو اللقطات المرسلة؛ يلزم جدول احتفاظ مؤسسي.','Device deletion does not erase downloads or sent snapshots; an institutional retention schedule is needed.'],
 ['19','TechnicalOrganisationalMeasure','الحماية','Safeguards','جزئي','Partial','تشفير AES-GCM للنسخ واللقطات، CSP، استعلام محلي للقراءة فقط، دون تحليلات مفعلة.','AES-GCM backups/snapshots, CSP, local read-only queries and disabled analytics.','التخزين المحلي المعتاد ليس خزنة مشفرة؛ يلزم تدقيق مستقل وتدابير تنظيمية.','Ordinary local storage is not an encrypted vault; independent review and organisational measures remain.'],
 ['20, 22','Risk','الحوادث وتقويم الأثر','Incidents and impact assessment','إجراء مؤسسي مطلوب','Institutional action required','حدود المخاطر موثقة؛ لا نجمع ملفات الطلاب مركزيًا.','Risk boundaries are documented; student profiles are not collected centrally.','إكمال تقويم الأثر وخطة استجابة للحوادث وتحديد المسؤوليات قبل التوسع.','Complete impact assessment, incident response and responsibilities before expansion.'],
 ['29','Processing','النقل خارج المملكة','International transfers','مراجعة مطلوبة','Review required','النص والسجل لا يرسلان إلى نموذج خارجي؛ تنزيل الأصول يمر عبر مزود الاستضافة.','Text and transcripts are not sent to external models; asset downloads use the hosting provider.','مراجعة سجلات IP والتشغيل لدى المزود وقنوات إرسال اللقطات وأي تكامل خارجي.','Review provider IP/operational logs, snapshot delivery channels and any external integration.'],
 ['31','DataController','سجل أنشطة المعالجة','Processing records','جزئي','Partial','الكود يوثق الأغراض والحدود. سجل استخدام الطالب محلي وليس سجل امتثال مؤسسيًا.','Code documents purposes and boundaries. A student’s local activity log is not an institutional compliance register.','إعداد سجل أنشطة رسمي يشمل الجهات والأغراض والاحتفاظ والمستلمين.','Prepare a formal register covering roles, purposes, retention and recipients.'],
]
export function pdplPage(lang){
 const ar=lang==='ar',t=(a,e)=>ar?a:e
 const table=`<div class="k-doc-table" role="region" tabindex="0" aria-label="${t('جدول مطابقة PDPL','PDPL mapping table')}"><table><thead><tr>${[t('مواد النظام','PDPL articles'),'DPV',t('الموضوع والحالة','Topic and status'),t('ما يطبقه كامن','Kamin implementation'),t('الفجوة المتبقية','Remaining gap')].map(s=>`<th scope="col">${s}</th>`).join('')}</tr></thead><tbody>${rows.map(([articles,term,at,et,as,es,ai,ei,ag,eg])=>`<tr><td><a href="${PDPL_SOURCE}">${articles}</a></td><td><a href="${DPV_SOURCE}#${term}"><code>dpv:${term}</code></a></td><td><strong>${t(at,et)}</strong><br>${t(as,es)}</td><td>${t(ai,ei)}</td><td>${t(ag,eg)}</td></tr>`).join('')}</tbody></table></div>`
 return [t('مطابقة PDPL وحالة التطبيق','PDPL mapping and implementation status'),t('ربط هندسي شفاف بمواد نظام حماية البيانات الشخصية السعودي، مع بيان ما يعمل والفجوات المتبقية.','A transparent engineering mapping to Saudi PDPL articles, showing working controls and remaining gaps.'),
 `<section class="k-doc-card"><h2>${t('نطاق هذه الصفحة','Scope of this page')}</h2><p>${t('تحديث: 30 سبتمبر 2026. هذه مطابقة هندسية أولية وليست شهادة امتثال أو رأيًا قانونيًا. لا تكتمل المتطلبات التنظيمية بمجرد تشغيل المعالجة داخل المتصفح. تُراجع الخريطة واللوائح مع الجهة المختصة قبل التبني المؤسسي.','Updated 30 September 2026. This preliminary engineering mapping is not a compliance certificate or legal opinion. Browser-only processing does not complete organisational requirements. Review the mapping and implementing regulations with the responsible institution before adoption.')}</p><p>${t('مفردات DPV من مجموعة مجتمع W3C تساعد على وصف الممارسات. وجودها في سجل الأنطولوجيا لا يعني تصدير إيصالات موافقة DPV كاملة؛ الخريطة أدناه تفسير للمشروع وليست مطابقة رسمية معتمدة.','DPV terms from a W3C Community Group help describe practices. Their presence in the ontology registry does not mean complete DPV consent receipts are exported. The mapping below is a project interpretation, not an officially approved equivalence.')}</p></section>`+table+
 `<section class="k-doc-card"><h2>${t('حدود تحتاج فهمًا واضحًا','Limits to understand')}</h2><p>${t('الاستدعاء الدلالي يعالج عبارة الاهتمام محليًا ولا يحفظها. ملفات النموذج عامة ويمكن حذف ذاكرته من الشاشة نفسها. رابط اللقطة يضم مفتاحها؛ من يحصل عليه يستطيع قراءتها وإعادة إرسالها. التشفير لا يثبت هوية المرسل أو صحة ادعائه ولا يمنع حفظ نسخة.','Semantic recall processes the interest phrase locally without saving it. Model files are public, and its cache can be deleted from the same screen. A snapshot link includes its key; its holder can read and forward it. Encryption does not authenticate the sender, verify claims or prevent copying.')}</p><p>${t('الاستضافة وخدمة توصيل الملفات قد تعالجان عنوان IP وبيانات الطلب وفق سياساتهما. عبارة «لا حساب مركزي» تخص ملف الطالب، ولا تعني عدم وجود أي بيانات تشغيل لدى مزود الاستضافة.','Hosting and asset delivery may process IP addresses and request metadata under provider policies. “No central account” describes the student profile; it does not mean the hosting provider has no operational data.')}</p><a href="/privacy.html">${t('سياسة الخصوصية','Privacy notice')}</a> · <a href="/guide.html">${t('دليل الاستخدام','User guide')}</a> · <a href="/contact.html">${t('الأسئلة وممارسة الحقوق','Questions and rights')}</a></section>`+
 `<section class="k-doc-card"><h2>${t('مصادر المراجعة والأدلة','Review sources and evidence')}</h2><p><a href="${PDPL_SOURCE}">${t('النظام — المنصة الوطنية لحوكمة البيانات، سدايا','Law — SDAIA National Data Governance Platform')}</a> · <a href="${DPV_SOURCE}">DPV 2.0 Community Group Report</a></p><p><a href="https://github.com/adeebnoor/KAMIN/tree/main/tests">${t('اختبارات السحب والتصدير والتشفير','Withdrawal, export and encryption tests')}</a> · <a href="https://github.com/adeebnoor/KAMIN/actions">${t('سجل التحقق الآلي','Automated verification history')}</a></p></section>`]
}
