export function validationRoadmap(lang){
 const t=(ar,en)=>lang==='ar'?ar:en
 const phases=[
 ['1–2',t('اعتماد النطاق والبروتوكول','Scope and protocol approval'),t('المشرف + الجهات المشاركة','Supervisor + participating institutions'),t('تحديد الكليات والموافقات والمقاييس ومسؤوليات البيانات. هدف: مراجعة 20 مسارًا على الأقل بواسطة مختصين اثنين قبل اعتماد الربط.','Confirm colleges, approvals, measures and data responsibilities. Target: two specialists review at least 20 pathways before mappings are accepted.')],
 ['2–3',t('اختبارات استخدام تكوينية','Formative usability'),t('فريق التجربة + المستشارون','UX team + advisors'),t('هدف: 12 طالبًا سعوديًا على جولتين، مع العربية والجوال. تُقاس ست مهام ببيانات وهمية وتُعالج العوائق قبل التوسع.','Target: 12 Saudi students over two rounds, including Arabic and mobile. Measure six tasks using synthetic records and resolve blockers before scaling.')],
 ['5–6',t('نموذج تحقق من المصدر','Issuer-verification prototype'),t('فريق الأدلة + جهة إصدار مخولة','Evidence team + authorized issuer'),t('هدف: 20 حالة اختبار اصطناعية تشمل التوقيع غير الصحيح والانتهاء والإلغاء. لا ترقية لمستوى مؤسسي قبل اجتياز الحالات السلبية ومراجعة أمنية.','Target: 20 synthetic test cases covering invalid signatures, expiry and revocation. No institutional evidence upgrades before negative cases and security review pass.')],
 ['3–4',t('تجربة استكشافية محددة بنهاية الفصل','Bounded end-of-semester pilot'),t('المشرف + الكليات الموافق عليها','Supervisor + approved colleges'),t('هدف: 60 مشاركًا، 20 لكل كلية. تعرض النجاحات المستقلة والمساعدة والفشل، وفواصل عدم اليقين، مع فصل نتائج اللغة والجهاز.','Target: 60 participants, 20 per college. Report independent completion, assistance and failure with uncertainty, separated by language and device.')],
 ['7–8',t('متابعة الاستخدام وإعادة التقييم','Follow-up and reevaluation'),t('الفريق + المستشارون','Team + advisors'),t('متابعة اختيارية معتمدة للمشاركين، ومقارنة الإصلاحات بخط البداية على مجموعة اختبار منفصلة؛ لا ادعاء أثر سببي على التوظيف.','Approved optional follow-up, comparing improvements with the baseline on a separate test set; no causal employment-effect claims.')],
 ['9',t('قرار الاستمرار والتسعير','Continuation and pricing decision'),t('المشرف + مركز الإرشاد','Supervisor + career center'),t('هدف: 5 مقابلات مع أصحاب قرار شراء ومراجعة النتائج والقيود وتكلفة التشغيل. لا انتقال لخدمة مدفوعة تلقائيًا.','Target: 5 interviews with purchasing decision-makers; review results, limitations and operating cost. No automatic transition to a paid service.')],
 ]
 return `<section class="card" id="roadmap"><span class="status planned">${t('مقترح مؤرخ 30 سبتمبر 2026 — لا نتائج','Proposal dated 30 September 2026 — no results')}</span><h2>${t('خطة التحقق خلال تسعة أشهر','Nine-month validation roadmap')}</h2><p>${t('يبدأ الشهر الأول بعد اعتماد البروتوكول والجهات المشاركة، وليس من تاريخ نشر الصفحة. التواريخ والمسؤوليات تحتاج تأكيد المشرف، ولا توجد شراكات أو عينات مجندة معلنة.','Month 1 starts after protocol and institutional approval, not when this page is published. Dates and responsibilities require supervisor confirmation; no partnerships or recruited samples are announced.')}</p><p>${t('هدف الفصل هو منتج قابل للاستخدام وتجربة أولية في الأسابيع 10–12 بعد الاعتماد؛ بقية الأشهر لتعميق التحقق والمتابعة، والشهر العاشر للتسليم النهائي. لا تؤجل هذه الخارطة تسليم الفصل.','The semester goal is a usable product and an initial study in weeks 10–12 after approval. Later months deepen validation and follow-up, with final handover in month ten. This roadmap does not postpone the semester deliverable.')}</p>${phases.sort((a,b)=>parseInt(a[0])-parseInt(b[0])).map(([m,title,owner,body])=>`<article><h3>${t('الشهر','Month')} ${m}: ${title}</h3><p><b>${owner}</b> · ${body}</p></article>`).join('')}</section>
 <section class="card"><h2>${t('عتبات مقترحة قبل التجربة — ليست نتائج','Proposed pre-pilot thresholds — not results')}</h2><ul><li>${t('إتمام مستقل ≥80% لكل مهمة أساسية؛ الفشل والمساعدة في المقام، ولا يُستبعد الانسحاب من التقرير.','Independent completion ≥80% per core task; failures and assisted attempts remain in the denominator, and withdrawals are reported.')}</li><li>${t('فهم المصدر وحد الاستنتاج (2 من 2) لدى ≥80% من المحاولات المؤهلة؛ ترميز بمراجعين لعينة محددة مسبقًا.','Source-and-limit comprehension (2 of 2) in ≥80% of eligible attempts; two reviewers code a prespecified subset.')}</li><li>${t('صفر ترقيات خاطئة للدليل في مجموعة اختبارات التحقق السلبية، وصفر عيوب خصوصية حرجة غير معالجة قبل تجربة سجلات حقيقية.','Zero false evidence upgrades in the negative verification suite and zero unresolved critical privacy defects before a real-record pilot.')}</li><li>${t('يُجمّد التعريف والعينة وقواعد التوقف قبل الدراسة. هذه أهداف لاتخاذ قرار الاستمرار وليست برهانًا على الدقة أو العدالة أو تحسن التوظيف.','Freeze definitions, sample and stopping rules before the study. These are continuation targets, not proof of accuracy, fairness or improved employment.')}</li></ul><p>${t('مهام الاستخدام: بناء ملف، تصحيح دليل، فهم توصية، اختيار خطوة، استعادة نسخة، والتصحيح والسحب والحذف. نشر النسب مع العدد وفواصل عدم اليقين؛ عدم تحقق الهدف يستدعي الإصلاح وإعادة القياس.','Usability tasks: build a profile, correct evidence, understand a recommendation, choose a step, restore a backup, and correct, withdraw and delete data. Report counts and uncertainty alongside rates; a missed target requires remediation and remeasurement.')}</p></section>`
}
