import {catalogExtension} from './catalogExtension.js'
export const TARGET_CATALOG_VERSION='kamin-targets-v2-20260930'

const rawTargetProfiles=[
  {
    id:'job-business-analyst',type:'job',
    title:{ar:'محلل أعمال',en:'Business Analyst'},
    subtitle:{ar:'ملف مهني مرجعي — غير إعلان وظيفة',en:'Reference occupation profile — not a job posting'},
    goals:['product','management'],
    requiredSkills:['requirements'],
    preferredInterests:['investigative','enterprising','conventional'],
    preferredValues:['achievement','independence','relationships'],
    preferredWorkStructure:['balanced','structured'],
    preferredCollaboration:['small-team','cross-functional','high-collaboration'],
    outcome:{ar:'تحويل احتياج العمل إلى متطلبات وحلول قابلة للتنفيذ.',en:'Translate business needs into actionable requirements and solutions.'},
  },
  {
    id:'job-data-analyst',type:'job',
    title:{ar:'محلل بيانات',en:'Data Analyst'},
    subtitle:{ar:'ملف مهني مرجعي — غير إعلان وظيفة',en:'Reference occupation profile — not a job posting'},
    goals:['data','product'],
    requiredSkills:['database','statistics'],
    occupationCodes:{esco:'2511.3',onet:'15-2051.01'},
    knowledgeGraph:'kamin-ict-kg-v1',
    preferredInterests:['investigative','conventional'],
    preferredValues:['achievement','independence'],
    preferredWorkStructure:['balanced','structured'],
    preferredCollaboration:['independent','small-team','cross-functional'],
    outcome:{ar:'تحويل البيانات إلى تحليلات قابلة للاستخدام في القرار.',en:'Turn data into analysis that supports decisions.'},
  },
  {
    id:'job-project-coordinator',type:'job',
    title:{ar:'منسق مشاريع تقنية',en:'IT Project Coordinator'},
    subtitle:{ar:'ملف مهني مرجعي — غير إعلان وظيفة',en:'Reference occupation profile — not a job posting'},
    goals:['management'],
    requiredSkills:['project'],
    preferredInterests:['enterprising','conventional','social'],
    preferredValues:['achievement','relationships','support'],
    preferredWorkStructure:['structured','balanced'],
    preferredCollaboration:['small-team','cross-functional','high-collaboration'],
    outcome:{ar:'تنسيق نطاق المشروع ومهامه وأصحاب المصلحة ومتابعة التنفيذ.',en:'Coordinate project scope, tasks, stakeholders, and execution.'},
  },
  {
    id:'job-software-engineer',type:'job',
    title:{ar:'مهندس برمجيات مبتدئ',en:'Junior Software Engineer'},
    subtitle:{ar:'ملف مهني مرجعي — غير إعلان وظيفة',en:'Reference occupation profile — not a job posting'},
    goals:['product'],
    requiredSkills:['software'],
    preferredInterests:['investigative','realistic'],
    preferredValues:['achievement','independence'],
    preferredWorkStructure:['balanced','flexible'],
    preferredCollaboration:['small-team','cross-functional'],
    outcome:{ar:'تصميم وتنفيذ واختبار مكونات برمجية ضمن فريق تطوير.',en:'Design, implement, and test software components within a development team.'},
  },
  {
    id:'job-cyber-analyst',type:'job',
    title:{ar:'محلل أمن سيبراني مبتدئ',en:'Junior Cybersecurity Analyst'},
    subtitle:{ar:'ملف مهني مرجعي — غير إعلان وظيفة',en:'Reference occupation profile — not a job posting'},
    goals:['cyber'],
    requiredSkills:['cyber'],
    preferredInterests:['investigative','realistic','conventional'],
    preferredValues:['achievement','support'],
    preferredWorkStructure:['structured','balanced'],
    preferredCollaboration:['small-team','cross-functional'],
    outcome:{ar:'مراقبة المخاطر وتطبيق ضوابط أساسية وتحليل التنبيهات الأمنية.',en:'Monitor risk, apply baseline controls, and analyze security alerts.'},
  },
  {
    id:'training-ai-work',type:'training',
    title:{ar:'مختبر توظيف الذكاء الاصطناعي في العمل',en:'AI-at-Work Practice Lab'},
    subtitle:{ar:'مسار تدريبي مرجعي',en:'Reference training pathway'},
    goals:['data','product','management','cyber'],
    requiredSkills:[],
    teachesSkills:['ai-work'],
    preferredInterests:['investigative','enterprising'],
    outcome:{ar:'إنتاج دليل تطبيقي على استخدام الذكاء الاصطناعي لإنجاز مهمة عمل قابلة للقياس.',en:'Produce applied evidence of using AI to complete a measurable work task.'},
  },
  {
    id:'training-data-portfolio',type:'training',
    title:{ar:'مشروع محفظة تحليل بيانات',en:'Data Analytics Portfolio Project'},
    subtitle:{ar:'مسار تدريبي مرجعي',en:'Reference training pathway'},
    goals:['data'],
    requiredSkills:['database'],
    teachesSkills:['statistics'],
    preferredInterests:['investigative','conventional'],
    outcome:{ar:'بناء مشروع تحليلي موثق يربط سؤال أعمال ببيانات ونتيجة قابلة للعرض.',en:'Build a documented analytics project linking a business question to data and a presentable result.'},
  },
  {
    id:'training-sql-analytics',type:'training',
    title:{ar:'مختبر SQL للتحليل',en:'SQL for Analytics Lab'},
    subtitle:{ar:'مسار تدريبي توضيحي — جسر فجوة',en:'Illustrative learning pathway — gap bridge'},
    goals:['data'],
    requiredSkills:[],
    teachesSkills:['database','sql'],
    preferredInterests:['investigative','conventional'],
    outcome:{ar:'بناء استعلامات وتحويلها إلى تحليل قابل للتكرار مع دليل تطبيقي.',en:'Build repeatable queries and turn them into an evidence-bearing analysis.'},
  },
  {
    id:'training-python-analytics',type:'training',
    title:{ar:'مختبر Python للتحليل',en:'Python Analytics Lab'},
    subtitle:{ar:'مسار تدريبي توضيحي — إشارة سوقية',en:'Illustrative learning pathway — market-signal bridge'},
    goals:['data'],
    requiredSkills:[],
    teachesSkills:['python'],
    preferredInterests:['investigative'],
    outcome:{ar:'إنتاج تحليل بيانات قابل لإعادة التشغيل باستخدام Python وإرفاقه كدليل.',en:'Produce a reproducible Python analysis and attach it as evidence.'},
  },
  {
    id:'training-bi-dashboard',type:'training',
    title:{ar:'مختبر لوحات ذكاء الأعمال',en:'BI Dashboard Lab'},
    subtitle:{ar:'مسار تدريبي توضيحي — إشارة سوقية',en:'Illustrative learning pathway — market-signal bridge'},
    goals:['data','product'],
    requiredSkills:['database'],
    teachesSkills:['data-visualization','power-bi'],
    preferredInterests:['investigative','conventional'],
    outcome:{ar:'تحويل سؤال عمل إلى لوحة بيانات مفسرة وقابلة للعرض كدليل.',en:'Turn a business question into an explainable dashboard that can serve as evidence.'},
  },
  {
    id:'training-product-discovery',type:'training',
    title:{ar:'مختبر اكتشاف المنتج وتحليل المتطلبات',en:'Product Discovery & Requirements Lab'},
    subtitle:{ar:'مسار تدريبي مرجعي',en:'Reference training pathway'},
    goals:['product'],
    requiredSkills:['requirements'],
    teachesSkills:['requirements'],
    preferredInterests:['investigative','enterprising','social'],
    outcome:{ar:'تحويل مشكلة مستخدم إلى فرضيات ومتطلبات ونموذج قرار أولي.',en:'Turn a user problem into hypotheses, requirements, and an initial decision model.'},
  },
]

export const targetProfiles=[...rawTargetProfiles,...catalogExtension].map(target=>({
  source:{title:'Kamin pilot catalog',url:'/methodology.html',checked:'2026-09-30',scope:'pilot-design'},
  mappingStatus:'pilot-authoring-not-institution-verified',
  ...target,
  occupationCodes:target.type==='job'
    ? {onet:null,esco:null,ssco:null,...(target.occupationCodes||{})}
    : undefined,
}))

export const targetTypes={
  job:{ar:'وظائف ومسارات مهنية',en:'Jobs & career paths'},
  training:{ar:'تدريب وتطبيق',en:'Training & applied learning'},
}
