export const KAMIN_ONTOLOGY_VERSION = '0.1.0'

export const NS = Object.freeze({
  kamin: 'https://adeebnoor.github.io/KAMIN/ontology/',
  schema: 'https://schema.org/',
  prov: 'http://www.w3.org/ns/prov#',
  skos: 'http://www.w3.org/2004/02/skos/core#',
  sh: 'http://www.w3.org/ns/shacl#',
  esco: 'http://data.europa.eu/esco/',
  elm: 'http://data.europa.eu/snb/model/ontology/',
  ctdl: 'https://purl.org/ctdl/terms/',
  ctdlasn: 'https://purl.org/ctdlasn/terms/',
  vc: 'https://www.w3.org/2018/credentials#',
  onet: 'https://www.onetcenter.org/',
  sasced: 'https://adeebnoor.github.io/KAMIN/reference/sasced/',
})

export const ASSERTION_KINDS = Object.freeze([
  'observed',     // imported from a source such as a transcript
  'declared',     // explicitly stated by the person
  'assessed',     // produced by a named assessment/instrument
  'inferred',     // generated by a rule/model and not independently verified
  'verified',     // confirmed by an authorized source
])

export const EVIDENCE_LEVELS = Object.freeze([
  'declared',
  'document',
  'assessed',
  'verified',
])

export const NODE_TYPES = Object.freeze({
  Person: {
    externalTypes: ['schema:Person'],
    description: 'The person at the center of the Kamin graph.',
  },
  AcademicProgram: {
    externalTypes: ['elm:LearningAchievementSpecification'],
    description: 'A formal academic programme or qualification context.',
  },
  Course: {
    externalTypes: ['schema:Course', 'elm:LearningOpportunity'],
    description: 'A formal or non-formal learning opportunity.',
  },
  LearningOutcome: {
    externalTypes: ['elm:LearningOutcome', 'ctdlasn:Competency'],
    description: 'An outcome expected or demonstrated through learning.',
  },
  Skill: {
    externalTypes: ['skos:Concept', 'ctdlasn:Competency'],
    preferredScheme: 'ESCO',
    description: 'A normalized skill or competence concept.',
  },
  Occupation: {
    externalTypes: ['schema:Occupation'],
    preferredScheme: 'ESCO',
    description: 'An occupation or occupational profile.',
  },
  Job: {
    externalTypes: ['schema:JobPosting'],
    description: 'A concrete role or opportunity.',
  },
  Training: {
    externalTypes: ['schema:Course', 'elm:LearningOpportunity'],
    description: 'A learning/training opportunity outside the academic programme.',
  },
  Credential: {
    externalTypes: ['schema:EducationalOccupationalCredential', 'vc:VerifiableCredential'],
    description: 'A degree, certificate, badge, licence or other credential.',
  },
  Achievement: {
    externalTypes: ['schema:Achievement'],
    description: 'An accomplishment or result supported by evidence.',
  },
  Evidence: {
    externalTypes: ['prov:Entity'],
    description: 'A source artifact supporting a claim.',
  },
  Assessment: {
    externalTypes: ['prov:Activity'],
    description: 'An assessment activity such as RIASEC, Big Five/IPIP, values or work style.',
  },
  Interest: {
    externalTypes: ['skos:Concept'],
    preferredScheme: 'O*NET-RIASEC',
    description: 'A career-interest concept.',
  },
  WorkValue: {
    externalTypes: ['skos:Concept'],
    preferredScheme: 'O*NET-WorkValues',
    description: 'A work-value concept.',
  },
  WorkStyle: {
    externalTypes: ['skos:Concept'],
    preferredScheme: 'O*NET-WorkStyles',
    description: 'A work-style concept.',
  },
  PersonalityTrait: {
    externalTypes: ['skos:Concept'],
    preferredScheme: 'IPIP',
    description: 'A psychometric trait concept represented as an assessment result, not a diagnosis.',
  },
  Motivation: {
    externalTypes: ['skos:Concept'],
    description: 'A structured motivation concept.',
  },
  Goal: {
    externalTypes: ['skos:Concept'],
    description: 'A declared career or learning goal.',
  },
  Constraint: {
    externalTypes: ['skos:Concept'],
    description: 'A declared constraint such as time, cost, location or modality.',
  },
  Outcome: {
    externalTypes: ['prov:Entity'],
    description: 'A real-world result used to validate or learn matching rules.',
  },
  MatchExplanation: {
    externalTypes: ['prov:Entity'],
    description: 'An explanation bundle for a computed fit or similarity relation.',
  },
})

export const EDGE_TYPES = Object.freeze({
  enrolledIn:      {from:['Person'],to:['AcademicProgram'],claim:'observed'},
  studied:         {from:['Person'],to:['Course'],claim:'observed'},
  completed:       {from:['Person'],to:['Course','Training'],claim:'observed'},
  achieved:        {from:['Person'],to:['Achievement'],claim:'observed'},
  holdsCredential: {from:['Person'],to:['Credential'],claim:'verified'},
  demonstrates:    {from:['Person'],to:['Skill'],claim:'inferred'},
  supportedBy:     {from:['Skill','Achievement','Credential','MatchExplanation'],to:['Evidence'],claim:null},
  hasLearningOutcome:{from:['Course','Training'],to:['LearningOutcome'],claim:'verified'},
  mapsToSkill:     {from:['LearningOutcome'],to:['Skill'],claim:'verified'},
  teachesSkill:    {from:['Course','Training'],to:['Skill'],claim:'verified'},
  requiresSkill:   {from:['Course','Training','Occupation','Job'],to:['Skill'],claim:'verified'},
  requiresCredential:{from:['Occupation','Job'],to:['Credential'],claim:'verified'},
  classifiedAs:    {from:['AcademicProgram'],to:['AcademicProgram'],claim:'verified'},
  interestedIn:    {from:['Person'],to:['Interest'],claim:'assessed'},
  values:          {from:['Person'],to:['WorkValue'],claim:'assessed'},
  prefersWorkStyle:{from:['Person'],to:['WorkStyle'],claim:'assessed'},
  hasTrait:        {from:['Person'],to:['PersonalityTrait'],claim:'assessed'},
  motivatedBy:     {from:['Person'],to:['Motivation'],claim:'assessed'},
  targets:         {from:['Person'],to:['Occupation','Job','Course','Training','Goal'],claim:'declared'},
  constrainedBy:   {from:['Person'],to:['Constraint'],claim:'declared'},
  producedOutcome: {from:['Person'],to:['Outcome'],claim:'observed'},
  similarTo:       {from:['Person','Course','Training','Occupation','Job'],to:['Person','Course','Training','Occupation','Job'],claim:'inferred'},
  complements:     {from:['Person'],to:['Person'],claim:'inferred'},
  fits:            {from:['Person'],to:['Course','Training','Occupation','Job'],claim:'inferred'},
  explainedBy:     {from:['MatchExplanation'],to:['Skill','Interest','WorkValue','WorkStyle','PersonalityTrait','Goal','Constraint','Evidence'],claim:'inferred'},
})

export function makeNode({id,type,label,scheme=null,externalId=null,metadata={}}){
  if(!id || !NODE_TYPES[type]) throw new Error('INVALID_ONTOLOGY_NODE')
  return {id,type,label:label||id,scheme,externalId,metadata}
}

export function makeEdge({
  id,
  type,
  from,
  to,
  assertionKind,
  source,
  timestamp=new Date().toISOString(),
  consentScope,
  ruleVersion=null,
  instrument=null,
  evidenceLevel=null,
  confidence=null,
  metadata={},
}){
  const spec=EDGE_TYPES[type]
  if(!id || !spec || !from || !to) throw new Error('INVALID_ONTOLOGY_EDGE')
  const kind=assertionKind || spec.claim
  if(kind && !ASSERTION_KINDS.includes(kind)) throw new Error('INVALID_ASSERTION_KIND')
  if(kind==='inferred' && !ruleVersion) throw new Error('INFERENCE_REQUIRES_RULE_VERSION')
  if(kind==='assessed' && !instrument) throw new Error('ASSESSMENT_REQUIRES_INSTRUMENT')
  if(['observed','assessed','verified'].includes(kind) && !source) throw new Error('CLAIM_REQUIRES_SOURCE')
  if(type==='demonstrates' && kind==='declared') throw new Error('DECLARATION_CANNOT_CREATE_DEMONSTRATED_SKILL')
  return {
    id,type,from,to,
    assertionKind:kind,
    source:source||null,
    timestamp,
    consentScope:consentScope||null,
    ruleVersion,
    instrument,
    evidenceLevel,
    confidence,
    metadata,
  }
}

export function validateGraph(graph){
  const errors=[]
  const nodes=new Map((graph?.nodes||[]).map(n=>[n.id,n]))
  for(const node of graph?.nodes||[]){
    if(!NODE_TYPES[node.type]) errors.push({code:'UNKNOWN_NODE_TYPE',node:node.id})
  }
  for(const edge of graph?.edges||[]){
    const spec=EDGE_TYPES[edge.type]
    const from=nodes.get(edge.from), to=nodes.get(edge.to)
    if(!spec) {errors.push({code:'UNKNOWN_EDGE_TYPE',edge:edge.id}); continue}
    if(!from || !to) {errors.push({code:'MISSING_ENDPOINT',edge:edge.id}); continue}
    if(!spec.from.includes(from.type)) errors.push({code:'INVALID_EDGE_SOURCE',edge:edge.id})
    if(!spec.to.includes(to.type)) errors.push({code:'INVALID_EDGE_TARGET',edge:edge.id})
    if(edge.assertionKind==='inferred' && !edge.ruleVersion) errors.push({code:'MISSING_RULE_VERSION',edge:edge.id})
    if(edge.assertionKind==='assessed' && !edge.instrument) errors.push({code:'MISSING_INSTRUMENT',edge:edge.id})
    if(['observed','assessed','verified'].includes(edge.assertionKind) && !edge.source) errors.push({code:'MISSING_SOURCE',edge:edge.id})
  }
  return {valid:errors.length===0,errors}
}
